using System.Collections.Generic;
#nullable enable

namespace MCDSaveEdit.Logic
{
    /// <summary>
    /// What a piece of gear is beyond its blueprint: its built-in skills, its property lines, and for
    /// an armor the armor properties it comes with.
    ///
    /// Both live in the item's compiled registry record, read off the running game
    /// (PROBE_RECORDS, 2026-09-26; melee, then =@ranged and =@armor) - no pak reaches them, and
    /// the item plugin writes a custom item's own (ItemPlugin: record +0x1B8, built-in
    /// enchantments; +0x70, property lines).
    ///
    ///   - A skill is a built-in enchantment: Firebrand's "Burns Mobs" is Fire Aspect, level 1. Its
    ///     tooltip line is the enchantment's own, added by the game when it draws the item, so it
    ///     is not listed here. Melee built-ins are all level 1; ranged ones reach further - every
    ///     Trickbow has Ricochet 99, which is why its arrows always bounce, and the Harpoon
    ///     Crossbow's unique has Piercing 3. Some bows' own mechanic is a built-in too: the Wind
    ///     Bow's pull, the Slow Bow's, the Hunting Bow's pet.
    ///   - A property line is tooltip text, "Dual Wield" or "Strong Charged Attacks". It describes
    ///     the weapon; what it does comes from the weapon an item is a copy of. Armor has none.
    ///   - Armor has built-in skills too (Frost Armor's Chilling 2, Gilded Glory's Death Barter), and
    ///     its default armor properties at record +0x1A8: EArmorPropertyID and EItemRarity, two
    ///     bytes each, a unique's own first. An owned armor's properties are the ones in the save;
    ///     these are what it drops with, and what the inventory's Defaults button gives it.
    ///
    /// Generated from that read, and from EEnchantmentTypeID in the Dumper-7 SDK dump. Regenerate
    /// after a game update that adds weapons.
    /// </summary>
    public static class GearTraits
    {
        /// <summary>EEnchantmentTypeID: the number the game stores for each enchantment.</summary>
        public static readonly IReadOnlyDictionary<string, int> ENCHANTMENT_IDS = new Dictionary<string, int>
        {
            ["Sharpness"] = 1,
            ["Knockback"] = 2,
            ["Looting"] = 3,
            ["Prospector"] = 4,
            ["FireAspect"] = 5,
            ["Rampaging"] = 6,
            ["Exploding"] = 7,
            ["CriticalHit"] = 8,
            ["Freezing"] = 9,
            ["PoisonedMelee"] = 10,
            ["JunglePoisonMelee"] = 11,
            ["Leeching"] = 12,
            ["Aiding"] = 13,
            ["GravityMelee"] = 14,
            ["EnigmaResonatorMelee"] = 15,
            ["AnimaConduitMelee"] = 16,
            ["Stunning"] = 17,
            ["CaveSpiderPoisonEnchantment"] = 18,
            ["Swirling"] = 19,
            ["Smiting"] = 20,
            ["Committed"] = 21,
            ["SoulSiphon"] = 22,
            ["RadianceMelee"] = 23,
            ["Chains"] = 24,
            ["Thundering"] = 25,
            ["Echo"] = 26,
            ["Shockwave"] = 27,
            ["Weakening"] = 28,
            ["BusyBee"] = 29,
            ["DynamoMelee"] = 30,
            ["BaneOfIllagers"] = 31,
            ["Rushdown"] = 32,
            ["SpongeStrike"] = 33,
            ["Heavyweight"] = 34,
            ["DamageSynergy"] = 35,
            ["PainCycle"] = 36,
            ["GuardingStrike"] = 37,
            ["PotionThirstMelee"] = 38,
            ["WitherEnchantmentMelee"] = 39,
            ["VoidTouchedMelee"] = 40,
            ["SharedPain"] = 41,
            ["BlindMelee"] = 42,
            ["Backstabber"] = 43,
            ["ShadowFlash"] = 44,
            ["DamageCounter"] = 45,
            ["ShadowFeast"] = 46,
            ["TempoTheft"] = 47,
            ["AlacrityAdjustment"] = 48,
            ["BowsBoon"] = 49,
            ["Ricochet"] = 50,
            ["Power"] = 51,
            ["Punch"] = 52,
            ["Infinity"] = 53,
            ["MultiShot"] = 54,
            ["Piercing"] = 55,
            ["ProjectileCounter"] = 56,
            ["ChainReaction"] = 57,
            ["Gravity"] = 58,
            ["HuntingBowEnchantment"] = 59,
            ["EnigmaResonatorRanged"] = 60,
            ["AnimaConduitRanged"] = 61,
            ["PoisonedRanged"] = 62,
            ["JunglePoisonRanged"] = 63,
            ["FreezingRanged"] = 64,
            ["RapidFire"] = 65,
            ["Supercharge"] = 66,
            ["BonusShot"] = 67,
            ["Unchanting"] = 68,
            ["FuseShot"] = 69,
            ["RadianceRanged"] = 70,
            ["Accelerating"] = 71,
            ["Growing"] = 72,
            ["WildRage"] = 73,
            ["SlowBowEnchantment"] = 74,
            ["DynamoRanged"] = 75,
            ["BurstBowstring"] = 76,
            ["ChargingAcceleration"] = 77,
            ["CogCrossbowEnchantment"] = 78,
            ["WindBowEnchantment"] = 79,
            ["ReliableRicochet"] = 80,
            ["MultiCharge"] = 81,
            ["PotionThirstRanged"] = 82,
            ["CooldownShot"] = 83,
            ["ArtifactCharge"] = 84,
            ["WitherEnchantmentRanged"] = 85,
            ["ShockWeb"] = 86,
            ["VoidTouchedRanged"] = 87,
            ["ShadowShot"] = 88,
            ["ShadowBarbRanged"] = 89,
            ["LevitationShot"] = 90,
            ["DippingPoison"] = 91,
            ["FreezingAoe"] = 92,
            ["Protection"] = 93,
            ["Celerity"] = 94,
            ["FinalShout"] = 95,
            ["Deflecting"] = 96,
            ["Regeneration"] = 97,
            ["Thorns"] = 98,
            ["AncientGuardianThorns"] = 99,
            ["Altruistic"] = 100,
            ["Shielding"] = 101,
            ["Barrier"] = 102,
            ["HuntingBowTaggedEnchantment"] = 103,
            ["Recycler"] = 104,
            ["Chilling"] = 105,
            ["Cowardice"] = 106,
            ["Electrified"] = 107,
            ["Burning"] = 108,
            ["Snowing"] = 109,
            ["GravityPulse"] = 110,
            ["FireTrail"] = 111,
            ["Frenzied"] = 112,
            ["Swiftfooted"] = 113,
            ["SpiritSpeed"] = 114,
            ["PotionFortification"] = 115,
            ["FoodReserves"] = 116,
            ["SurpriseGift"] = 117,
            ["DoubleDamage"] = 118,
            ["FastAttack"] = 119,
            ["Quick"] = 120,
            ["HealthSynergy"] = 121,
            ["SpeedSynergy"] = 122,
            ["Explorer"] = 123,
            ["VesselTrail"] = 124,
            ["SlowResistance"] = 125,
            ["SlowImmunity"] = 126,
            ["TumbleBee"] = 127,
            ["BagOfSouls"] = 128,
            ["Acrobat"] = 129,
            ["PushVolumeImmunity"] = 130,
            ["WindResistance"] = 131,
            ["WindImmunity"] = 132,
            ["RollCharge"] = 133,
            ["MultiDodge"] = 134,
            ["EmeraldDivination"] = 135,
            ["DeathBarter"] = 136,
            ["ResurrectionSurge"] = 137,
            ["Huge"] = 138,
            ["ResurrectSurroundingMobs"] = 139,
            ["Invisible"] = 140,
            ["PoisonFocus"] = 141,
            ["FireFocus"] = 142,
            ["SoulFocus"] = 143,
            ["LightningFocus"] = 144,
            ["Flee"] = 145,
            ["BeastSurge"] = 146,
            ["BeastBurst"] = 147,
            ["BeastBoss"] = 148,
            ["Reckless"] = 149,
            ["CurrentImmunity"] = 150,
            ["CurrentResistance"] = 151,
            ["ThriveUnderPressure"] = 152,
            ["VoidBlast"] = 153,
            ["ShulkerSentry"] = 154,
            ["LuckOfTheSea"] = 155,
            ["UnderwaterImmunity"] = 156,
            ["PlayerIdle"] = 157,
            ["BardIdle"] = 158,
            ["BardUnique1Idle"] = 159,
            ["PassiveRegen"] = 160,
            ["VoidStrikeImmunity"] = 161,
        };

        /// <summary>Every skill a weapon of each type has built in in the game: what a custom one can pick.</summary>
        public static readonly IReadOnlyDictionary<CustomItems.Kind, IReadOnlyList<string>> SKILLS = new Dictionary<CustomItems.Kind, IReadOnlyList<string>>
        {
            [CustomItems.Kind.Melee] = new string[]
            {
                "Backstabber",
                "BaneOfIllagers",
                "BusyBee",
                "Chains",
                "Committed",
                "CriticalHit",
                "DynamoMelee",
                "Echo",
                "EnigmaResonatorMelee",
                "Exploding",
                "FireAspect",
                "Freezing",
                "GravityMelee",
                "Heavyweight",
                "JunglePoisonMelee",
                "Leeching",
                "Looting",
                "PoisonedMelee",
                "Prospector",
                "RadianceMelee",
                "Rampaging",
                "Rushdown",
                "SharedPain",
                "Sharpness",
                "Shockwave",
                "Smiting",
                "SoulSiphon",
                "SpongeStrike",
                "Stunning",
                "Swirling",
                "Thundering",
                "VoidTouchedMelee",
                "Weakening",
            },
            [CustomItems.Kind.Ranged] = new string[]
            {
                "Accelerating",
                "BonusShot",
                "ChainReaction",
                "CogCrossbowEnchantment",
                "DynamoRanged",
                "EnigmaResonatorRanged",
                "FuseShot",
                "Gravity",
                "Growing",
                "HuntingBowEnchantment",
                "Infinity",
                "MultiShot",
                "Piercing",
                "PoisonedRanged",
                "Power",
                "Punch",
                "RadianceRanged",
                "RapidFire",
                "ReliableRicochet",
                "Ricochet",
                "RollCharge",
                "ShadowBarbRanged",
                "ShadowShot",
                "SlowBowEnchantment",
                "Supercharge",
                "TempoTheft",
                "Unchanting",
                "VoidTouchedRanged",
                "WildRage",
                "WindBowEnchantment",
            },
            [CustomItems.Kind.Armor] = new string[]
            {
                "Acrobat",
                "BagOfSouls",
                "BardIdle",
                "BardUnique1Idle",
                "Burning",
                "Chilling",
                "DeathBarter",
                "Deflecting",
                "EmeraldDivination",
                "FireTrail",
                "Flee",
                "FoodReserves",
                "MultiDodge",
                "PotionFortification",
                "ShulkerSentry",
                "Snowing",
                "SurpriseGift",
                "Swiftfooted",
                "ThriveUnderPressure",
                "VoidBlast",
            },
            [CustomItems.Kind.Artifact] = new string[]
            {
            },
        };

        /// <summary>Every property line a weapon of each type shows in the game, by its ItemType key, with its English.</summary>
        public static readonly IReadOnlyDictionary<CustomItems.Kind, IReadOnlyDictionary<string, string>> LINES = new Dictionary<CustomItems.Kind, IReadOnlyDictionary<string, string>>
        {
            [CustomItems.Kind.Melee] = new Dictionary<string, string>
            {
                ["continuous_attacks"] = "Continuous attacks",
                ["dual_wield"] = "Dual Wield",
                ["fast_thrusts"] = "Fast Thrusts",
                ["great_pushback"] = "Great Pushback",
                ["great_splash"] = "Great Splash",
                ["long_continuous_attacks"] = "Long Continuous Attacks",
                ["long_melee_reach"] = "Long Melee Reach",
                ["longer_melee_reach"] = "Longer Melee Reach",
                ["powerful_pushback"] = "Powerful Pushback",
                ["rapid_slashes"] = "Rapid Slashes",
                ["relentless_combo"] = "Relentless Combo",
                ["reliable_combo"] = "Reliable Combo",
                ["slow_but_powerful"] = "Slow but Powerful",
                ["spin_attack"] = "Spin attack",
                ["spin_attack_move"] = "Spin attack move",
                ["stylish_combo"] = "Stylish Combo",
                ["thrust_attack"] = "Thrust attack",
                ["turbo_punches"] = "Turbo Punches",
                ["powerful_combo"] = "Very powerful combo",
            },
            [CustomItems.Kind.Armor] = new Dictionary<string, string>
            {
            },
            [CustomItems.Kind.Artifact] = new Dictionary<string, string>
            {
                ["roll_trigger"] = "Activates Rolling Triggers",
                ["grapple vines"] = "Briefly entangles mobs",
                ["poison grapple vines"] = "Poisons entangled mobs",
                ["stuns_mobs_ice"] = "Stuns Mobs for 2 seconds",
            },
            [CustomItems.Kind.Ranged] = new Dictionary<string, string>
            {
                ["bubbled_when_charged"] = "Bubble damage",
                ["double_projectiles"] = "Double Projectiles",
                ["even_more_projectiles"] = "Even More Projectiles",
                ["explodes_on_impact"] = "Explodes on Impact",
                ["fast_multiple_projectiles"] = "Fast Multiple Projectiles",
                ["faster_projectiles"] = "Faster Projectiles",
                ["chared_fires_three_arrows"] = "Fires 3 arrows when charged",
                ["fires_harpoons"] = "Fires Harpoons",
                ["high_firerate"] = "High Firerate",
                ["multiple_projectiles"] = "Multiple projectiles",
                ["Characteristic_TwistingVineBow"] = "Poison Trail",
                ["powerful_shots"] = "Powerful Shots",
                ["strong_charged_attacks"] = "Strong Charged Attacks",
            },
        };

        /// <summary>Each game weapon's and armor's own built-in skills (name, level) and property lines (keys).</summary>
        public static readonly IReadOnlyDictionary<string, (IReadOnlyList<(string skill, int level)> skills, IReadOnlyList<string> lines)> WEAPONS =
            new Dictionary<string, (IReadOnlyList<(string, int)>, IReadOnlyList<string>)>(System.StringComparer.OrdinalIgnoreCase)
        {
            //Melee
            ["Anchor"] = (new (string, int)[] { ("Heavyweight", 1), ("GravityMelee", 1) }, new string[] { "slow_but_powerful" }),
            ["Anchor_Unique1"] = (new (string, int)[] { ("JunglePoisonMelee", 1), ("Heavyweight", 1), ("GravityMelee", 1) }, new string[] { "slow_but_powerful" }),
            ["Axe"] = (new (string, int)[] { }, new string[] { "spin_attack_move" }),
            ["Axe_Unique1"] = (new (string, int)[] { ("FireAspect", 1) }, new string[] { "spin_attack_move" }),
            ["Axe_Unique2"] = (new (string, int)[] { ("Stunning", 1) }, new string[] { "spin_attack_move" }),
            ["Backstabber"] = (new (string, int)[] { ("Backstabber", 1) }, new string[] { }),
            ["Backstabber_Unique1"] = (new (string, int)[] { ("Backstabber", 1), ("Echo", 1) }, new string[] { }),
            ["Battlestaff"] = (new (string, int)[] { }, new string[] { "stylish_combo" }),
            ["Battlestaff_Unique1"] = (new (string, int)[] { ("Committed", 1) }, new string[] { "stylish_combo" }),
            ["Battlestaff_Unique2"] = (new (string, int)[] { ("Exploding", 1) }, new string[] { "stylish_combo" }),
            ["Boneclub"] = (new (string, int)[] { }, new string[] { "great_pushback" }),
            ["Boneclub_Unique1"] = (new (string, int)[] { ("BaneOfIllagers", 1) }, new string[] { "great_pushback" }),
            ["Chainsword"] = (new (string, int)[] { }, new string[] { "continuous_attacks" }),
            ["Chainsword_Unique1"] = (new (string, int)[] { }, new string[] { "long_continuous_attacks" }),
            ["Claymore"] = (new (string, int)[] { }, new string[] { "powerful_pushback" }),
            ["Claymore_Unique1"] = (new (string, int)[] { ("Leeching", 1) }, new string[] { "powerful_pushback" }),
            ["Claymore_Unique2"] = (new (string, int)[] { ("Sharpness", 1) }, new string[] { "powerful_pushback" }),
            ["Claymore_Unique3"] = (new (string, int)[] { ("DynamoMelee", 1) }, new string[] { "powerful_pushback" }),
            ["Claymore_Winter1"] = (new (string, int)[] { ("Sharpness", 1) }, new string[] { "powerful_pushback" }),
            ["CoralBlade"] = (new (string, int)[] { }, new string[] { "rapid_slashes" }),
            ["CoralBlade_Unique1"] = (new (string, int)[] { ("SpongeStrike", 1) }, new string[] { "rapid_slashes" }),
            ["Cutlass"] = (new (string, int)[] { }, new string[] { "reliable_combo" }),
            ["Cutlass_Unique1"] = (new (string, int)[] { ("Weakening", 1) }, new string[] { "reliable_combo" }),
            ["Cutlass_Unique2"] = (new (string, int)[] { ("Rampaging", 1) }, new string[] { "reliable_combo" }),
            ["Cutlass_Year1"] = (new (string, int)[] { ("Rampaging", 1) }, new string[] { "reliable_combo" }),
            ["Daggers"] = (new (string, int)[] { }, new string[] { "dual_wield" }),
            ["Daggers_Unique1"] = (new (string, int)[] { ("Freezing", 1) }, new string[] { "dual_wield" }),
            ["Daggers_Unique2"] = (new (string, int)[] { ("EnigmaResonatorMelee", 1) }, new string[] { "dual_wield" }),
            ["Daggers_Unique3"] = (new (string, int)[] { ("Swirling", 1) }, new string[] { "dual_wield" }),
            ["DoubleAxe"] = (new (string, int)[] { }, new string[] { "spin_attack" }),
            ["DoubleAxe_Unique1"] = (new (string, int)[] { ("Shockwave", 1) }, new string[] { "spin_attack" }),
            ["DoubleAxe_Unique2"] = (new (string, int)[] { ("Exploding", 1) }, new string[] { "spin_attack" }),
            ["Gauntlets"] = (new (string, int)[] { }, new string[] { "relentless_combo" }),
            ["Gauntlets_Unique1"] = (new (string, int)[] { ("EnigmaResonatorMelee", 1) }, new string[] { "relentless_combo" }),
            ["Gauntlets_Unique2"] = (new (string, int)[] { ("Rampaging", 1) }, new string[] { "relentless_combo" }),
            ["Gauntlets_Unique3"] = (new (string, int)[] { }, new string[] { "turbo_punches" }),
            ["Glaive"] = (new (string, int)[] { }, new string[] { "longer_melee_reach" }),
            ["Glaive_Spooky2"] = (new (string, int)[] { ("Smiting", 1) }, new string[] { "longer_melee_reach" }),
            ["Glaive_Unique1"] = (new (string, int)[] { ("Smiting", 1) }, new string[] { "longer_melee_reach" }),
            ["Glaive_Unique2"] = (new (string, int)[] { ("PoisonedMelee", 1) }, new string[] { "longer_melee_reach" }),
            ["Hammer"] = (new (string, int)[] { }, new string[] { "great_splash" }),
            ["Hammer_Unique1"] = (new (string, int)[] { ("Thundering", 1) }, new string[] { "great_splash" }),
            ["Hammer_Unique2"] = (new (string, int)[] { ("GravityMelee", 1) }, new string[] { "great_splash" }),
            ["Katana"] = (new (string, int)[] { }, new string[] { }),
            ["Katana_Unique1"] = (new (string, int)[] { ("CriticalHit", 1) }, new string[] { }),
            ["Katana_Unique2"] = (new (string, int)[] { ("Smiting", 1) }, new string[] { }),
            ["Mace"] = (new (string, int)[] { }, new string[] { }),
            ["Mace_Unique1"] = (new (string, int)[] { ("RadianceMelee", 1) }, new string[] { }),
            ["Mace_Unique2"] = (new (string, int)[] { ("Chains", 1) }, new string[] { }),
            ["ObsidianClaymore"] = (new (string, int)[] { }, new string[] { "powerful_combo" }),
            ["ObsidianClaymore_Unique1"] = (new (string, int)[] { ("SharedPain", 1) }, new string[] { "powerful_combo" }),
            ["Pickaxe"] = (new (string, int)[] { }, new string[] { }),
            ["Pickaxe_Unique1"] = (new (string, int)[] { ("Prospector", 1) }, new string[] { }),
            ["Rapier"] = (new (string, int)[] { }, new string[] { "fast_thrusts" }),
            ["Rapier_Unique1"] = (new (string, int)[] { ("BusyBee", 1) }, new string[] { "fast_thrusts" }),
            ["Rapier_Unique2"] = (new (string, int)[] { ("Freezing", 1) }, new string[] { "fast_thrusts" }),
            ["Sickles"] = (new (string, int)[] { }, new string[] { "dual_wield" }),
            ["Sickles_Unique1"] = (new (string, int)[] { ("PoisonedMelee", 1) }, new string[] { "dual_wield" }),
            ["Sickles_Unique2"] = (new (string, int)[] { ("Prospector", 1) }, new string[] { "dual_wield" }),
            ["SkeletonHammer"] = (new (string, int)[] { ("GravityMelee", 1) }, new string[] { "great_splash" }),
            ["SoulKnife"] = (new (string, int)[] { }, new string[] { "thrust_attack" }),
            ["SoulKnife_Unique1"] = (new (string, int)[] { ("Committed", 1) }, new string[] { "thrust_attack" }),
            ["SoulKnife_Unique2"] = (new (string, int)[] { ("SoulSiphon", 1) }, new string[] { "thrust_attack" }),
            ["SoulScythe"] = (new (string, int)[] { }, new string[] { }),
            ["SoulScythe_Spooky2"] = (new (string, int)[] { ("Freezing", 1) }, new string[] { }),
            ["SoulScythe_Unique1"] = (new (string, int)[] { ("Chains", 1) }, new string[] { }),
            ["SoulScythe_Unique2"] = (new (string, int)[] { ("Freezing", 1) }, new string[] { }),
            ["Spear"] = (new (string, int)[] { }, new string[] { "long_melee_reach" }),
            ["Spear_spooky2"] = (new (string, int)[] { ("Echo", 1) }, new string[] { "long_melee_reach" }),
            ["Spear_Unique1"] = (new (string, int)[] { ("Echo", 1) }, new string[] { "long_melee_reach" }),
            ["Spear_Unique2"] = (new (string, int)[] { ("Looting", 1) }, new string[] { "long_melee_reach" }),
            ["Sword"] = (new (string, int)[] { }, new string[] { }),
            ["Sword_Spooky1"] = (new (string, int)[] { ("CriticalHit", 1) }, new string[] { }),
            ["Sword_Unique1"] = (new (string, int)[] { ("Sharpness", 1) }, new string[] { }),
            ["Sword_Unique2"] = (new (string, int)[] { ("CriticalHit", 1) }, new string[] { }),
            ["TempestKnife"] = (new (string, int)[] { ("Rushdown", 1) }, new string[] { }),
            ["TempestKnife_Unique1"] = (new (string, int)[] { ("Rushdown", 1), ("Committed", 1) }, new string[] { }),
            ["TempestKnife_Unique2"] = (new (string, int)[] { ("Rushdown", 1), ("Freezing", 1) }, new string[] { }),
            ["VoidTouchedBlades"] = (new (string, int)[] { ("VoidTouchedMelee", 1) }, new string[] { }),
            ["VoidTouchedBlades_Unique1"] = (new (string, int)[] { ("Leeching", 1), ("VoidTouchedMelee", 1) }, new string[] { }),
            ["Whip"] = (new (string, int)[] { }, new string[] { "longer_melee_reach" }),
            ["Whip_Unique1"] = (new (string, int)[] { ("JunglePoisonMelee", 1) }, new string[] { "longer_melee_reach" }),
            //Ranged
            ["BatCrossbow"] = (new (string, int)[] { ("ShadowShot", 1), ("ShadowBarbRanged", 1) }, new string[] { }),
            ["Bow"] = (new (string, int)[] { }, new string[] { }),
            ["Bow_Spooky1"] = (new (string, int)[] { ("BonusShot", 1) }, new string[] { }),
            ["Bow_Unique1"] = (new (string, int)[] { ("Growing", 1) }, new string[] { }),
            ["Bow_Unique2"] = (new (string, int)[] { ("BonusShot", 1) }, new string[] { }),
            ["BubbleBow"] = (new (string, int)[] { }, new string[] { "bubbled_when_charged" }),
            ["BubbleBow_Spooky2"] = (new (string, int)[] { ("ReliableRicochet", 1) }, new string[] { "bubbled_when_charged" }),
            ["BubbleBow_Unique1"] = (new (string, int)[] { ("ReliableRicochet", 1) }, new string[] { "bubbled_when_charged" }),
            ["BurstCrossbow"] = (new (string, int)[] { }, new string[] { "fast_multiple_projectiles" }),
            ["BurstCrossbow_Unique1"] = (new (string, int)[] { ("EnigmaResonatorRanged", 1) }, new string[] { "fast_multiple_projectiles" }),
            ["BurstCrossbow_Unique2"] = (new (string, int)[] { ("DynamoRanged", 1) }, new string[] { "fast_multiple_projectiles" }),
            ["CogCrossbow"] = (new (string, int)[] { ("CogCrossbowEnchantment", 1) }, new string[] { }),
            ["CogCrossbow_Unique1"] = (new (string, int)[] { ("Piercing", 1), ("CogCrossbowEnchantment", 1) }, new string[] { }),
            ["Crossbow"] = (new (string, int)[] { }, new string[] { "faster_projectiles" }),
            ["Crossbow_Unique1"] = (new (string, int)[] { ("Piercing", 1) }, new string[] { "faster_projectiles" }),
            ["Crossbow_Unique2"] = (new (string, int)[] { ("RapidFire", 1) }, new string[] { "faster_projectiles" }),
            ["DualCrossbows"] = (new (string, int)[] { }, new string[] { "double_projectiles" }),
            ["DualCrossbows_Unique1"] = (new (string, int)[] { ("Unchanting", 1) }, new string[] { "double_projectiles" }),
            ["DualCrossbows_Unique2"] = (new (string, int)[] { ("Growing", 1) }, new string[] { "double_projectiles" }),
            ["ExplodingCrossbow"] = (new (string, int)[] { }, new string[] { "explodes_on_impact" }),
            ["ExplodingCrossbow_Unique1"] = (new (string, int)[] { ("Gravity", 1) }, new string[] { "explodes_on_impact" }),
            ["ExplodingCrossbow_Unique2"] = (new (string, int)[] { ("ChainReaction", 1) }, new string[] { "explodes_on_impact" }),
            ["HarpoonCrossbow"] = (new (string, int)[] { }, new string[] { "fires_harpoons" }),
            ["HarpoonCrossbow_Unique1"] = (new (string, int)[] { ("Piercing", 3) }, new string[] { "fires_harpoons" }),
            ["HeavyCrossbow"] = (new (string, int)[] { }, new string[] { "powerful_shots" }),
            ["HeavyCrossbow_Unique1"] = (new (string, int)[] { ("Punch", 1) }, new string[] { "powerful_shots" }),
            ["HeavyCrossbow_Unique2"] = (new (string, int)[] { ("Ricochet", 1) }, new string[] { "powerful_shots" }),
            ["HuntingBow"] = (new (string, int)[] { ("HuntingBowEnchantment", 1) }, new string[] { }),
            ["HuntingBow_Unique1"] = (new (string, int)[] { ("HuntingBowEnchantment", 1), ("Infinity", 1) }, new string[] { }),
            ["HuntingBow_Unique2"] = (new (string, int)[] { ("HuntingBowEnchantment", 1), ("Power", 1) }, new string[] { }),
            ["HuntingBow_Unique3"] = (new (string, int)[] { ("HuntingBowEnchantment", 1), ("DynamoRanged", 1) }, new string[] { }),
            ["Longbow"] = (new (string, int)[] { }, new string[] { "strong_charged_attacks" }),
            ["Longbow_Unique1"] = (new (string, int)[] { ("Supercharge", 1) }, new string[] { "strong_charged_attacks" }),
            ["Longbow_Unique2"] = (new (string, int)[] { ("FuseShot", 1) }, new string[] { "strong_charged_attacks" }),
            ["Powerbow"] = (new (string, int)[] { }, new string[] { "strong_charged_attacks" }),
            ["PowerBow_Spooky2"] = (new (string, int)[] { ("Power", 1) }, new string[] { "strong_charged_attacks" }),
            ["Powerbow_Unique1"] = (new (string, int)[] { ("Power", 1) }, new string[] { "strong_charged_attacks" }),
            ["Powerbow_Unique2"] = (new (string, int)[] { ("RadianceRanged", 1) }, new string[] { "strong_charged_attacks" }),
            ["RapidCrossbow"] = (new (string, int)[] { }, new string[] { "high_firerate" }),
            ["RapidCrossbow_Unique1"] = (new (string, int)[] { ("BonusShot", 1) }, new string[] { "high_firerate" }),
            ["RapidCrossbow_Unique2"] = (new (string, int)[] { ("Accelerating", 1) }, new string[] { "high_firerate" }),
            ["ScatterCrossbow"] = (new (string, int)[] { }, new string[] { "multiple_projectiles" }),
            ["ScatterCrossbow_Unique1"] = (new (string, int)[] { }, new string[] { "even_more_projectiles" }),
            ["ScatterCrossbow_Unique2"] = (new (string, int)[] { ("Ricochet", 1) }, new string[] { "multiple_projectiles" }),
            ["ShadowCrossbow"] = (new (string, int)[] { ("ShadowShot", 1) }, new string[] { }),
            ["ShadowCrossbow_Unique1"] = (new (string, int)[] { ("ShadowShot", 1), ("ShadowBarbRanged", 1) }, new string[] { }),
            ["Shortbow"] = (new (string, int)[] { }, new string[] { }),
            ["Shortbow_Unique1"] = (new (string, int)[] { ("RapidFire", 1) }, new string[] { }),
            ["Shortbow_Unique2"] = (new (string, int)[] { ("Accelerating", 1) }, new string[] { }),
            ["Shortbow_Unique3"] = (new (string, int)[] { ("WildRage", 1) }, new string[] { }),
            ["SlowBow"] = (new (string, int)[] { ("SlowBowEnchantment", 1) }, new string[] { }),
            ["SlowBow_Spooky2"] = (new (string, int)[] { ("SlowBowEnchantment", 1) }, new string[] { "chared_fires_three_arrows" }),
            ["SlowBow_Unique1"] = (new (string, int)[] { ("SlowBowEnchantment", 1) }, new string[] { "chared_fires_three_arrows" }),
            ["SoulBow"] = (new (string, int)[] { }, new string[] { }),
            ["SoulBow_Unique1"] = (new (string, int)[] { ("TempoTheft", 1) }, new string[] { }),
            ["SoulBow_Unique2"] = (new (string, int)[] { ("MultiShot", 1) }, new string[] { }),
            ["SoulBow_Winter1"] = (new (string, int)[] { ("TempoTheft", 1) }, new string[] { }),
            ["SoulCrossbow"] = (new (string, int)[] { }, new string[] { }),
            ["SoulCrossbow_Unique1"] = (new (string, int)[] { ("EnigmaResonatorRanged", 1) }, new string[] { }),
            ["SoulCrossbow_Unique2"] = (new (string, int)[] { ("Gravity", 1) }, new string[] { }),
            ["Trickbow"] = (new (string, int)[] { ("Ricochet", 99) }, new string[] { }),
            ["Trickbow_Unique1"] = (new (string, int)[] { ("PoisonedRanged", 1), ("Ricochet", 99) }, new string[] { }),
            ["Trickbow_Unique2"] = (new (string, int)[] { ("WildRage", 1), ("Ricochet", 99) }, new string[] { }),
            ["Trickbow_Year1"] = (new (string, int)[] { ("WildRage", 1), ("Ricochet", 99) }, new string[] { }),
            ["TwistingVineBow"] = (new (string, int)[] { }, new string[] { "Characteristic_TwistingVineBow" }),
            ["TwistingVineBow_Unique1"] = (new (string, int)[] { ("RollCharge", 1) }, new string[] { }),
            ["VoidBow"] = (new (string, int)[] { ("VoidTouchedRanged", 1) }, new string[] { }),
            ["VoidBow_Unique1"] = (new (string, int)[] { ("VoidTouchedRanged", 1), ("FuseShot", 1) }, new string[] { }),
            ["WindBow"] = (new (string, int)[] { ("WindBowEnchantment", 1) }, new string[] { }),
            ["WindBow_Unique1"] = (new (string, int)[] { ("WindBowEnchantment", 1), ("Ricochet", 1) }, new string[] { }),
            ["WindBow_Unique2"] = (new (string, int)[] { ("WindBowEnchantment", 1), ("RollCharge", 1) }, new string[] { }),
            //Armor
            ["ArchersStrappings"] = (new (string, int)[] { }, new string[] { }),
            ["ArchersStrappings_Unique1"] = (new (string, int)[] { }, new string[] { }),
            ["AssassinArmor"] = (new (string, int)[] { }, new string[] { }),
            ["AssassinArmor_Unique1"] = (new (string, int)[] { }, new string[] { }),
            ["BardsGarb"] = (new (string, int)[] { ("BardIdle", 1) }, new string[] { }),
            ["BardsGarb_Unique1"] = (new (string, int)[] { ("BardUnique1Idle", 1) }, new string[] { }),
            ["BattleRobe"] = (new (string, int)[] { }, new string[] { }),
            ["BattleRobe_Unique1"] = (new (string, int)[] { }, new string[] { }),
            ["BeenestArmor"] = (new (string, int)[] { }, new string[] { }),
            ["BeenestArmor_Unique1"] = (new (string, int)[] { }, new string[] { }),
            ["ChampionsArmor"] = (new (string, int)[] { }, new string[] { }),
            ["ChampionsArmor_Unique1"] = (new (string, int)[] { }, new string[] { }),
            ["ClimbingGear"] = (new (string, int)[] { }, new string[] { }),
            ["ClimbingGear_Unique1"] = (new (string, int)[] { }, new string[] { }),
            ["ClimbingGear_Unique2"] = (new (string, int)[] { ("MultiDodge", 1) }, new string[] { }),
            ["CowardsArmor"] = (new (string, int)[] { }, new string[] { }),
            ["DarkArmor"] = (new (string, int)[] { }, new string[] { }),
            ["DarkArmor_Unique1"] = (new (string, int)[] { }, new string[] { }),
            ["EmeraldArmor"] = (new (string, int)[] { ("EmeraldDivination", 1) }, new string[] { }),
            ["EmeraldArmor_Unique1"] = (new (string, int)[] { ("EmeraldDivination", 1) }, new string[] { }),
            ["EmeraldArmor_Unique2"] = (new (string, int)[] { ("EmeraldDivination", 1), ("DeathBarter", 1) }, new string[] { }),
            ["EndRobes"] = (new (string, int)[] { }, new string[] { }),
            ["EndRobes_Unique1"] = (new (string, int)[] { ("VoidBlast", 1) }, new string[] { }),
            ["EvocationRobe"] = (new (string, int)[] { }, new string[] { }),
            ["EvocationRobe_Unique1"] = (new (string, int)[] { ("Burning", 1) }, new string[] { }),
            ["EvocationRobe_Unique2"] = (new (string, int)[] { ("BagOfSouls", 1) }, new string[] { }),
            ["FullPlateArmor"] = (new (string, int)[] { }, new string[] { }),
            ["FullPlateArmor_Spooky2"] = (new (string, int)[] { }, new string[] { }),
            ["FullPlateArmor_Unique1"] = (new (string, int)[] { }, new string[] { }),
            ["GhostArmor"] = (new (string, int)[] { }, new string[] { }),
            ["GhostArmor_Spooky2"] = (new (string, int)[] { ("FireTrail", 1) }, new string[] { }),
            ["GhostArmor_Unique1"] = (new (string, int)[] { ("FireTrail", 1) }, new string[] { }),
            ["GrimArmor"] = (new (string, int)[] { }, new string[] { }),
            ["GrimArmor_Spooky2"] = (new (string, int)[] { }, new string[] { }),
            ["GrimArmor_Unique1"] = (new (string, int)[] { }, new string[] { }),
            ["MercenaryArmor"] = (new (string, int)[] { }, new string[] { }),
            ["MercenaryArmor_Spooky1"] = (new (string, int)[] { }, new string[] { }),
            ["MercenaryArmor_Spooky2"] = (new (string, int)[] { }, new string[] { }),
            ["MercenaryArmor_Unique1"] = (new (string, int)[] { }, new string[] { }),
            ["MysteryArmor"] = (new (string, int)[] { }, new string[] { }),
            ["NatureArmor"] = (new (string, int)[] { }, new string[] { }),
            ["NatureArmor_Unique1"] = (new (string, int)[] { ("FoodReserves", 1) }, new string[] { }),
            ["OcelotArmor"] = (new (string, int)[] { }, new string[] { }),
            ["OcelotArmor_Unique1"] = (new (string, int)[] { }, new string[] { }),
            ["PhantomArmor"] = (new (string, int)[] { }, new string[] { }),
            ["PhantomArmor_Unique1"] = (new (string, int)[] { ("Snowing", 1) }, new string[] { }),
            ["PiglinArmor"] = (new (string, int)[] { }, new string[] { }),
            ["PiglinArmor_Unique1"] = (new (string, int)[] { ("SurpriseGift", 1) }, new string[] { }),
            ["ReinforcedMail"] = (new (string, int)[] { }, new string[] { }),
            ["ReinforcedMail_Unique1"] = (new (string, int)[] { ("PotionFortification", 1) }, new string[] { }),
            ["ScaleMail"] = (new (string, int)[] { }, new string[] { }),
            ["ScaleMail_Unique1"] = (new (string, int)[] { ("Swiftfooted", 1) }, new string[] { }),
            ["ShulkerArmor"] = (new (string, int)[] { ("Deflecting", 1), ("ThriveUnderPressure", 1) }, new string[] { }),
            ["ShulkerArmor_Unique1"] = (new (string, int)[] { ("Deflecting", 1), ("ThriveUnderPressure", 1), ("ShulkerSentry", 1) }, new string[] { }),
            ["SnowArmor"] = (new (string, int)[] { }, new string[] { }),
            ["SnowArmor_Unique1"] = (new (string, int)[] { ("Chilling", 2) }, new string[] { }),
            ["SoulRobe"] = (new (string, int)[] { }, new string[] { }),
            ["SoulRobe_Unique1"] = (new (string, int)[] { }, new string[] { }),
            ["SpelunkersArmor"] = (new (string, int)[] { }, new string[] { }),
            ["SpelunkersArmor_Unique1"] = (new (string, int)[] { }, new string[] { }),
            ["SpelunkersArmor_Year1"] = (new (string, int)[] { }, new string[] { }),
            ["SproutArmor"] = (new (string, int)[] { }, new string[] { }),
            ["SproutArmor_Unique1"] = (new (string, int)[] { ("Acrobat", 1) }, new string[] { }),
            ["SquidArmor"] = (new (string, int)[] { }, new string[] { }),
            ["SquidArmor_Unique1"] = (new (string, int)[] { }, new string[] { }),
            ["TurtleArmor"] = (new (string, int)[] { }, new string[] { }),
            ["TurtleArmor_Unique1"] = (new (string, int)[] { ("Flee", 1) }, new string[] { }),
            ["WolfArmor"] = (new (string, int)[] { }, new string[] { }),
            ["WolfArmor_Unique1"] = (new (string, int)[] { }, new string[] { }),
            ["WolfArmor_Unique2"] = (new (string, int)[] { ("Acrobat", 1) }, new string[] { }),
            ["WolfArmor_Winter1"] = (new (string, int)[] { }, new string[] { }),
            //Artifact
            ["BeeNest"] = (new (string, int)[] { }, new string[] { }),
            ["BootsOfSwiftness"] = (new (string, int)[] { }, new string[] { }),
            ["ChargedRedstoneMines"] = (new (string, int)[] { }, new string[] { }),
            ["CorruptedBeacon"] = (new (string, int)[] { }, new string[] { }),
            ["CorruptedBeacon_Spooky1"] = (new (string, int)[] { }, new string[] { }),
            ["CorruptedSeeds"] = (new (string, int)[] { }, new string[] { "grapple vines", "poison grapple vines" }),
            ["DeathCapMushroom"] = (new (string, int)[] { }, new string[] { }),
            ["EnchantersTome"] = (new (string, int)[] { }, new string[] { }),
            ["FireworksArrowItem"] = (new (string, int)[] { }, new string[] { }),
            ["FishingRod"] = (new (string, int)[] { }, new string[] { }),
            ["FlamingQuiver"] = (new (string, int)[] { }, new string[] { }),
            ["GhostCloak"] = (new (string, int)[] { }, new string[] { }),
            ["GolemKit"] = (new (string, int)[] { }, new string[] { }),
            ["GongOfWeakening"] = (new (string, int)[] { }, new string[] { }),
            ["GuardianEye"] = (new (string, int)[] { }, new string[] { }),
            ["Harvester"] = (new (string, int)[] { }, new string[] { }),
            ["HeavyHarpoonQuiver"] = (new (string, int)[] { }, new string[] { }),
            ["IceWand"] = (new (string, int)[] { }, new string[] { "stuns_mobs_ice" }),
            ["IronHideAmulet"] = (new (string, int)[] { }, new string[] { }),
            ["LightFeather"] = (new (string, int)[] { }, new string[] { "roll_trigger" }),
            ["LightningRod"] = (new (string, int)[] { }, new string[] { }),
            ["LostEvocation"] = (new (string, int)[] { }, new string[] { }),
            ["LoveMedallion"] = (new (string, int)[] { }, new string[] { }),
            ["MobMasher"] = (new (string, int)[] { }, new string[] { }),
            ["NetherWartSporeGrenade"] = (new (string, int)[] { }, new string[] { }),
            ["RainbowGrass"] = (new (string, int)[] { }, new string[] { }),
            ["SatchelOfNeed"] = (new (string, int)[] { }, new string[] { }),
            ["SatchelOfNourishment"] = (new (string, int)[] { }, new string[] { }),
            ["SatchelOfTheElements"] = (new (string, int)[] { }, new string[] { }),
            ["ShadowSplinter"] = (new (string, int)[] { }, new string[] { }),
            ["ShockPowder"] = (new (string, int)[] { }, new string[] { }),
            ["SoulHealer"] = (new (string, int)[] { }, new string[] { }),
            ["SoulLantern"] = (new (string, int)[] { }, new string[] { }),
            ["SoulTotemOfCasting"] = (new (string, int)[] { }, new string[] { }),
            ["SpinWheel"] = (new (string, int)[] { }, new string[] { }),
            ["TastyBone"] = (new (string, int)[] { }, new string[] { }),
            ["ThunderingQuiver"] = (new (string, int)[] { }, new string[] { }),
            ["TomeOfDuplication"] = (new (string, int)[] { }, new string[] { }),
            ["TormentQuiver"] = (new (string, int)[] { }, new string[] { }),
            ["TotemOfRegeneration"] = (new (string, int)[] { }, new string[] { }),
            ["TotemOfShielding"] = (new (string, int)[] { }, new string[] { }),
            ["UpdraftTome"] = (new (string, int)[] { }, new string[] { }),
            ["VoidQuiver"] = (new (string, int)[] { }, new string[] { }),
            ["WindHorn"] = (new (string, int)[] { }, new string[] { }),
            ["WonderfulWheat"] = (new (string, int)[] { }, new string[] { }),
        };

        /// <summary>
        /// Each game artifact's numbers, plain floats in its record: soul cost (+0x94), cooldown in
        /// seconds (+0x98), and duration in seconds (+0x9C). 0 where it has none.
        /// </summary>
        public static readonly IReadOnlyDictionary<string, (double souls, double cooldown, double duration)> ARTIFACT_NUMBERS =
            new Dictionary<string, (double, double, double)>(System.StringComparer.OrdinalIgnoreCase)
        {
            ["BeeNest"] = (0, 23, 16),
            ["BootsOfSwiftness"] = (0, 5, 1.5),
            ["ChargedRedstoneMines"] = (0, 12, 0),
            ["CorruptedBeacon"] = (2, 2.5, 0),
            ["CorruptedBeacon_Spooky1"] = (2, 2.5, 0),
            ["CorruptedSeeds"] = (0, 10, 3),
            ["DeathCapMushroom"] = (0, 30, 8),
            ["EnchantersTome"] = (0, 15, 8),
            ["FireworksArrowItem"] = (0, 30, 10),
            ["FishingRod"] = (0, 1.5, 0),
            ["FlamingQuiver"] = (0, 30, 0),
            ["GhostCloak"] = (0, 6, 1.5),
            ["GolemKit"] = (0, 30, 0),
            ["GongOfWeakening"] = (0, 20, 5),
            ["GuardianEye"] = (0, 22, 4),
            ["Harvester"] = (40, 4, 0),
            ["HeavyHarpoonQuiver"] = (0, 30, 0),
            ["IceWand"] = (0, 15, 5),
            ["IronHideAmulet"] = (0, 25, 8),
            ["LightFeather"] = (0, 3, 0),
            ["LightningRod"] = (15, 2, 0),
            ["LostEvocation"] = (0, 30, 0),
            ["LoveMedallion"] = (0, 30, 0),
            ["MobMasher"] = (0, 10, 15),
            ["NetherWartSporeGrenade"] = (0, 6, 0),
            ["RainbowGrass"] = (0, 30, 0),
            ["SatchelOfNeed"] = (0, 25, 0),
            ["SatchelOfNourishment"] = (0, 16, 0),
            ["SatchelOfTheElements"] = (0, 10, 0),
            ["ShadowSplinter"] = (0.33, 5, 10),
            ["ShockPowder"] = (0, 15, 3),
            ["SoulHealer"] = (50, 5, 0),
            ["SoulLantern"] = (60, 5, 30),
            ["SoulTotemOfCasting"] = (70, 10, 5),
            ["SpinWheel"] = (0, 5, 0),
            ["TastyBone"] = (0, 30, 0),
            ["ThunderingQuiver"] = (0, 30, 0),
            ["TomeOfDuplication"] = (40, 10, 0),
            ["TormentQuiver"] = (30, 6, 0),
            ["TotemOfRegeneration"] = (0, 25, 10),
            ["TotemOfShielding"] = (0, 20, 5),
            ["UpdraftTome"] = (0, 10, 0),
            ["VoidQuiver"] = (0, 25, 0),
            ["WindHorn"] = (0, 10, 0),
            ["WonderfulWheat"] = (0, 30, 0),
        };

        /// <summary>EArmorPropertyID: the number the game stores for each armor property.</summary>
        public static readonly IReadOnlyDictionary<string, int> ARMOR_PROPERTY_IDS = new Dictionary<string, int>
        {
            ["SoulGatheringBoost"] = 1,
            ["SuperbDamageAbsorption"] = 2,
            ["MissChance"] = 3,
            ["TeleportChance"] = 4,
            ["ItemDamageBoost"] = 5,
            ["ItemCooldownDecrease"] = 6,
            ["AllyDamageBoost"] = 7,
            ["IncreasedArrowBundleSize"] = 8,
            ["MeleeDamageBoost"] = 9,
            ["MeleeAttackSpeedBoost"] = 10,
            ["RangedDamageBoost"] = 11,
            ["LifeStealAura"] = 12,
            ["MoveSpeedAura"] = 13,
            ["PetBat"] = 14,
            ["AreaHeal"] = 15,
            ["MoveSpeedReduction"] = 16,
            ["IncreasedMobTargeting"] = 17,
            ["PotionCooldownDecrease"] = 18,
            ["DodgeCooldownIncrease"] = 19,
            ["DodgeSpeedIncrease"] = 20,
            ["DodgeInvulnerability"] = 21,
            ["DamageAbsorption"] = 22,
            ["SlowResistance"] = 23,
            ["DodgeGhostForm"] = 24,
            ["Beekeeper"] = 25,
            ["DodgeRoot"] = 26,
            ["Heavyweight"] = 27,
            ["EnvironmentalProtection"] = 28,
            ["EmeraldShield"] = 29,
            ["ItemCooldownReset"] = 30,
            ["SquidRollQuick"] = 31,
            ["SquidRollLimited"] = 32,
            ["HealingAura"] = 33,
            ["FallResistance"] = 34,
            ["SquidRoll"] = 35,
            ["Resonant"] = 36,
            ["ImmunityBoost"] = 37,
            ["InstantTransmission"] = 38,
            ["Last"] = 39,
        };

        /// <summary>Every armor property an armor in the game comes with: what a custom one can pick.</summary>
        public static readonly IReadOnlyList<string> ARMOR_PROPERTIES = new[]
        {
            "AllyDamageBoost",
            "AreaHeal",
            "Beekeeper",
            "DodgeCooldownIncrease",
            "DodgeGhostForm",
            "DodgeInvulnerability",
            "DodgeRoot",
            "DodgeSpeedIncrease",
            "EmeraldShield",
            "EnvironmentalProtection",
            "HealingAura",
            "Heavyweight",
            "ImmunityBoost",
            "IncreasedArrowBundleSize",
            "IncreasedMobTargeting",
            "InstantTransmission",
            "ItemCooldownDecrease",
            "ItemCooldownReset",
            "ItemDamageBoost",
            "LifeStealAura",
            "MeleeAttackSpeedBoost",
            "MeleeDamageBoost",
            "MissChance",
            "MoveSpeedAura",
            "PetBat",
            "PotionCooldownDecrease",
            "RangedDamageBoost",
            "Resonant",
            "SlowResistance",
            "SoulGatheringBoost",
            "SquidRollLimited",
            "SquidRollQuick",
            "SuperbDamageAbsorption",
        };

        /// <summary>Each game armor's default properties (id, rarity: 0 common, 2 unique), in the game's order.</summary>
        public static readonly IReadOnlyDictionary<string, IReadOnlyList<(string property, int rarity)>> ARMOR_DEFAULTS =
            new Dictionary<string, IReadOnlyList<(string, int)>>(System.StringComparer.OrdinalIgnoreCase)
        {
            ["ArchersStrappings"] = new (string, int)[] { ("IncreasedArrowBundleSize", 0), ("RangedDamageBoost", 0) },
            ["ArchersStrappings_Unique1"] = new (string, int)[] { ("MoveSpeedAura", 2), ("IncreasedArrowBundleSize", 0), ("RangedDamageBoost", 0) },
            ["AssassinArmor"] = new (string, int)[] { ("MeleeAttackSpeedBoost", 0) },
            ["AssassinArmor_Unique1"] = new (string, int)[] { ("LifeStealAura", 2), ("MeleeAttackSpeedBoost", 0) },
            ["BardsGarb"] = new (string, int)[] { ("AreaHeal", 0), ("Resonant", 0) },
            ["BardsGarb_Unique1"] = new (string, int)[] { ("ImmunityBoost", 2), ("AreaHeal", 0), ("Resonant", 0) },
            ["BattleRobe"] = new (string, int)[] { ("ItemCooldownDecrease", 0), ("MeleeDamageBoost", 0) },
            ["BattleRobe_Unique1"] = new (string, int)[] { ("ItemDamageBoost", 2), ("ItemCooldownDecrease", 0), ("MeleeDamageBoost", 0) },
            ["BeenestArmor"] = new (string, int)[] { ("Beekeeper", 0), ("AreaHeal", 0) },
            ["BeenestArmor_Unique1"] = new (string, int)[] { ("SuperbDamageAbsorption", 2), ("Beekeeper", 0), ("AreaHeal", 0) },
            ["ChampionsArmor"] = new (string, int)[] { ("SuperbDamageAbsorption", 0), ("IncreasedMobTargeting", 0), ("PotionCooldownDecrease", 0) },
            ["ChampionsArmor_Unique1"] = new (string, int)[] { ("AreaHeal", 2), ("SuperbDamageAbsorption", 0), ("IncreasedMobTargeting", 0), ("PotionCooldownDecrease", 0) },
            ["ClimbingGear"] = new (string, int)[] { ("ItemCooldownDecrease", 0), ("Heavyweight", 0) },
            ["ClimbingGear_Unique1"] = new (string, int)[] { ("EnvironmentalProtection", 2), ("SlowResistance", 2), ("ItemCooldownDecrease", 0), ("Heavyweight", 0) },
            ["ClimbingGear_Unique2"] = new (string, int)[] { ("ItemCooldownDecrease", 0), ("Heavyweight", 0) },
            ["CowardsArmor"] = new (string, int)[] { ("ItemCooldownDecrease", 0), ("IncreasedArrowBundleSize", 0) },
            ["DarkArmor"] = new (string, int)[] { ("SoulGatheringBoost", 0), ("SuperbDamageAbsorption", 0) },
            ["DarkArmor_Unique1"] = new (string, int)[] { ("AllyDamageBoost", 2), ("SoulGatheringBoost", 0), ("SuperbDamageAbsorption", 0) },
            ["EmeraldArmor"] = new (string, int)[] { ("MeleeAttackSpeedBoost", 0) },
            ["EmeraldArmor_Unique1"] = new (string, int)[] { ("EmeraldShield", 2), ("MeleeAttackSpeedBoost", 0) },
            ["EmeraldArmor_Unique2"] = new (string, int)[] { ("MeleeAttackSpeedBoost", 0) },
            ["EndRobes"] = new (string, int)[] { ("InstantTransmission", 0), ("SoulGatheringBoost", 0) },
            ["EndRobes_Unique1"] = new (string, int)[] { ("InstantTransmission", 0), ("SoulGatheringBoost", 0) },
            ["EvocationRobe"] = new (string, int)[] { ("ItemCooldownDecrease", 0), ("MoveSpeedAura", 0) },
            ["EvocationRobe_Unique1"] = new (string, int)[] { ("ItemCooldownDecrease", 0), ("MoveSpeedAura", 0) },
            ["EvocationRobe_Unique2"] = new (string, int)[] { ("ItemCooldownDecrease", 0), ("MoveSpeedAura", 0) },
            ["FullPlateArmor"] = new (string, int)[] { ("MissChance", 0), ("SuperbDamageAbsorption", 0), ("DodgeCooldownIncrease", 0) },
            ["FullPlateArmor_Spooky2"] = new (string, int)[] { ("MeleeDamageBoost", 2), ("MissChance", 0), ("SuperbDamageAbsorption", 0), ("DodgeCooldownIncrease", 0) },
            ["FullPlateArmor_Unique1"] = new (string, int)[] { ("MeleeDamageBoost", 2), ("MissChance", 0), ("SuperbDamageAbsorption", 0), ("DodgeCooldownIncrease", 0) },
            ["GhostArmor"] = new (string, int)[] { ("DodgeGhostForm", 0), ("MissChance", 0) },
            ["GhostArmor_Spooky2"] = new (string, int)[] { ("DodgeGhostForm", 0), ("MissChance", 0) },
            ["GhostArmor_Unique1"] = new (string, int)[] { ("DodgeGhostForm", 0), ("MissChance", 0) },
            ["GrimArmor"] = new (string, int)[] { ("SoulGatheringBoost", 0), ("LifeStealAura", 0) },
            ["GrimArmor_Spooky2"] = new (string, int)[] { ("SuperbDamageAbsorption", 2), ("SoulGatheringBoost", 0), ("LifeStealAura", 0) },
            ["GrimArmor_Unique1"] = new (string, int)[] { ("SuperbDamageAbsorption", 2), ("SoulGatheringBoost", 0), ("LifeStealAura", 0) },
            ["MercenaryArmor"] = new (string, int)[] { ("SuperbDamageAbsorption", 0), ("AllyDamageBoost", 0) },
            ["MercenaryArmor_Spooky1"] = new (string, int)[] { ("MeleeAttackSpeedBoost", 2), ("SuperbDamageAbsorption", 0), ("AllyDamageBoost", 0) },
            ["MercenaryArmor_Spooky2"] = new (string, int)[] { ("MeleeAttackSpeedBoost", 2), ("SuperbDamageAbsorption", 0), ("AllyDamageBoost", 0) },
            ["MercenaryArmor_Unique1"] = new (string, int)[] { ("MeleeAttackSpeedBoost", 2), ("SuperbDamageAbsorption", 0), ("AllyDamageBoost", 0) },
            ["MysteryArmor"] = new (string, int)[] { },
            ["NatureArmor"] = new (string, int)[] { ("ItemCooldownReset", 0), ("AreaHeal", 0) },
            ["NatureArmor_Unique1"] = new (string, int)[] { ("ItemCooldownReset", 0), ("AreaHeal", 0) },
            ["OcelotArmor"] = new (string, int)[] { ("DodgeSpeedIncrease", 0), ("SuperbDamageAbsorption", 0) },
            ["OcelotArmor_Unique1"] = new (string, int)[] { ("DodgeInvulnerability", 2), ("DodgeSpeedIncrease", 0), ("SuperbDamageAbsorption", 0) },
            ["PhantomArmor"] = new (string, int)[] { ("SoulGatheringBoost", 0), ("RangedDamageBoost", 0) },
            ["PhantomArmor_Unique1"] = new (string, int)[] { ("SoulGatheringBoost", 0), ("RangedDamageBoost", 0) },
            ["PiglinArmor"] = new (string, int)[] { ("ItemCooldownReset", 0), ("ItemDamageBoost", 0) },
            ["PiglinArmor_Unique1"] = new (string, int)[] { ("ItemCooldownReset", 0), ("ItemDamageBoost", 0) },
            ["ReinforcedMail"] = new (string, int)[] { ("SuperbDamageAbsorption", 0), ("MissChance", 0), ("DodgeCooldownIncrease", 0) },
            ["ReinforcedMail_Unique1"] = new (string, int)[] { ("SuperbDamageAbsorption", 0), ("MissChance", 0), ("DodgeCooldownIncrease", 0) },
            ["ScaleMail"] = new (string, int)[] { ("SuperbDamageAbsorption", 0), ("MeleeDamageBoost", 0) },
            ["ScaleMail_Unique1"] = new (string, int)[] { ("SuperbDamageAbsorption", 0), ("MeleeDamageBoost", 0) },
            ["ShulkerArmor"] = new (string, int)[] { ("IncreasedMobTargeting", 0) },
            ["ShulkerArmor_Unique1"] = new (string, int)[] { ("IncreasedMobTargeting", 0) },
            ["SnowArmor"] = new (string, int)[] { ("SuperbDamageAbsorption", 0), ("SlowResistance", 0) },
            ["SnowArmor_Unique1"] = new (string, int)[] { ("SuperbDamageAbsorption", 0), ("SlowResistance", 0) },
            ["SoulRobe"] = new (string, int)[] { ("SoulGatheringBoost", 0), ("ItemDamageBoost", 0) },
            ["SoulRobe_Unique1"] = new (string, int)[] { ("MissChance", 2), ("SoulGatheringBoost", 0), ("ItemDamageBoost", 0) },
            ["SpelunkersArmor"] = new (string, int)[] { ("AllyDamageBoost", 0), ("PetBat", 0) },
            ["SpelunkersArmor_Unique1"] = new (string, int)[] { ("ItemDamageBoost", 2), ("AllyDamageBoost", 0), ("PetBat", 0) },
            ["SpelunkersArmor_Year1"] = new (string, int)[] { ("ItemDamageBoost", 2), ("AllyDamageBoost", 0), ("PetBat", 0) },
            ["SproutArmor"] = new (string, int)[] { ("AreaHeal", 0), ("DodgeRoot", 0) },
            ["SproutArmor_Unique1"] = new (string, int)[] { ("AreaHeal", 0), ("DodgeRoot", 0) },
            ["SquidArmor"] = new (string, int)[] { ("MoveSpeedAura", 0), ("SquidRollLimited", 0) },
            ["SquidArmor_Unique1"] = new (string, int)[] { ("DodgeInvulnerability", 2), ("SquidRollQuick", 0), ("MoveSpeedAura", 0) },
            ["TurtleArmor"] = new (string, int)[] { ("SuperbDamageAbsorption", 0), ("HealingAura", 0) },
            ["TurtleArmor_Unique1"] = new (string, int)[] { ("SuperbDamageAbsorption", 0), ("HealingAura", 0) },
            ["WolfArmor"] = new (string, int)[] { ("AllyDamageBoost", 0), ("AreaHeal", 0) },
            ["WolfArmor_Unique1"] = new (string, int)[] { ("MissChance", 2), ("AllyDamageBoost", 0), ("AreaHeal", 0) },
            ["WolfArmor_Unique2"] = new (string, int)[] { ("AllyDamageBoost", 0), ("AreaHeal", 0) },
            ["WolfArmor_Winter1"] = new (string, int)[] { ("MissChance", 2), ("AllyDamageBoost", 0), ("AreaHeal", 0) },
        };
    }
}
