using System.Collections.Generic;
#nullable enable

namespace MCDSaveEdit.Logic
{
    /// <summary>
    /// What a melee weapon is beyond its blueprint: its built-in skills and its property lines.
    ///
    /// Both live in the item's compiled registry record, read off the running game
    /// (PROBE_RECORDS, 2026-09-26) - no pak reaches them, and the item plugin writes a custom
    /// item's own (ItemPlugin: record +0x1B8, built-in enchantments; +0x70, property lines).
    ///
    ///   - A skill is a built-in enchantment: Firebrand's "Burns Mobs" is Fire Aspect, level 1. Its
    ///     tooltip line is the enchantment's own, added by the game when it draws the item, so it
    ///     is not listed here. Every built-in the game ships is level 1.
    ///   - A property line is tooltip text, "Dual Wield" or "Spin attack". It describes the moveset;
    ///     the move itself comes from the attacks of the weapon an item is a copy of.
    ///
    /// Generated from that read, and from EEnchantmentTypeID in the Dumper-7 SDK dump. Regenerate
    /// both after a game update that adds weapons.
    /// </summary>
    public static class MeleeTraits
    {
        /// <summary>EEnchantmentTypeID: the number the game stores for each enchantment.</summary>
        public static readonly IReadOnlyDictionary<string, int> ENCHANTMENT_IDS = new Dictionary<string, int>
        {
            ["Sharpness"] = 1,
            ["Knockback"] = 2,
            ["Looting"] = 3,
            ["Prospector"] = 4,
            ["FireAspect"] = 5,
            ["Rampaging"] = 6,
            ["Exploding"] = 7,
            ["CriticalHit"] = 8,
            ["Freezing"] = 9,
            ["PoisonedMelee"] = 10,
            ["JunglePoisonMelee"] = 11,
            ["Leeching"] = 12,
            ["Aiding"] = 13,
            ["GravityMelee"] = 14,
            ["EnigmaResonatorMelee"] = 15,
            ["AnimaConduitMelee"] = 16,
            ["Stunning"] = 17,
            ["CaveSpiderPoisonEnchantment"] = 18,
            ["Swirling"] = 19,
            ["Smiting"] = 20,
            ["Committed"] = 21,
            ["SoulSiphon"] = 22,
            ["RadianceMelee"] = 23,
            ["Chains"] = 24,
            ["Thundering"] = 25,
            ["Echo"] = 26,
            ["Shockwave"] = 27,
            ["Weakening"] = 28,
            ["BusyBee"] = 29,
            ["DynamoMelee"] = 30,
            ["BaneOfIllagers"] = 31,
            ["Rushdown"] = 32,
            ["SpongeStrike"] = 33,
            ["Heavyweight"] = 34,
            ["DamageSynergy"] = 35,
            ["PainCycle"] = 36,
            ["GuardingStrike"] = 37,
            ["PotionThirstMelee"] = 38,
            ["WitherEnchantmentMelee"] = 39,
            ["VoidTouchedMelee"] = 40,
            ["SharedPain"] = 41,
            ["BlindMelee"] = 42,
            ["Backstabber"] = 43,
            ["ShadowFlash"] = 44,
            ["DamageCounter"] = 45,
            ["ShadowFeast"] = 46,
            ["TempoTheft"] = 47,
            ["AlacrityAdjustment"] = 48,
            ["BowsBoon"] = 49,
            ["Ricochet"] = 50,
            ["Power"] = 51,
            ["Punch"] = 52,
            ["Infinity"] = 53,
            ["MultiShot"] = 54,
            ["Piercing"] = 55,
            ["ProjectileCounter"] = 56,
            ["ChainReaction"] = 57,
            ["Gravity"] = 58,
            ["HuntingBowEnchantment"] = 59,
            ["EnigmaResonatorRanged"] = 60,
            ["AnimaConduitRanged"] = 61,
            ["PoisonedRanged"] = 62,
            ["JunglePoisonRanged"] = 63,
            ["FreezingRanged"] = 64,
            ["RapidFire"] = 65,
            ["Supercharge"] = 66,
            ["BonusShot"] = 67,
            ["Unchanting"] = 68,
            ["FuseShot"] = 69,
            ["RadianceRanged"] = 70,
            ["Accelerating"] = 71,
            ["Growing"] = 72,
            ["WildRage"] = 73,
            ["SlowBowEnchantment"] = 74,
            ["DynamoRanged"] = 75,
            ["BurstBowstring"] = 76,
            ["ChargingAcceleration"] = 77,
            ["CogCrossbowEnchantment"] = 78,
            ["WindBowEnchantment"] = 79,
            ["ReliableRicochet"] = 80,
            ["MultiCharge"] = 81,
            ["PotionThirstRanged"] = 82,
            ["CooldownShot"] = 83,
            ["ArtifactCharge"] = 84,
            ["WitherEnchantmentRanged"] = 85,
            ["ShockWeb"] = 86,
            ["VoidTouchedRanged"] = 87,
            ["ShadowShot"] = 88,
            ["ShadowBarbRanged"] = 89,
            ["LevitationShot"] = 90,
            ["DippingPoison"] = 91,
            ["FreezingAoe"] = 92,
            ["Protection"] = 93,
            ["Celerity"] = 94,
            ["FinalShout"] = 95,
            ["Deflecting"] = 96,
            ["Regeneration"] = 97,
            ["Thorns"] = 98,
            ["AncientGuardianThorns"] = 99,
            ["Altruistic"] = 100,
            ["Shielding"] = 101,
            ["Barrier"] = 102,
            ["HuntingBowTaggedEnchantment"] = 103,
            ["Recycler"] = 104,
            ["Chilling"] = 105,
            ["Cowardice"] = 106,
            ["Electrified"] = 107,
            ["Burning"] = 108,
            ["Snowing"] = 109,
            ["GravityPulse"] = 110,
            ["FireTrail"] = 111,
            ["Frenzied"] = 112,
            ["Swiftfooted"] = 113,
            ["SpiritSpeed"] = 114,
            ["PotionFortification"] = 115,
            ["FoodReserves"] = 116,
            ["SurpriseGift"] = 117,
            ["DoubleDamage"] = 118,
            ["FastAttack"] = 119,
            ["Quick"] = 120,
            ["HealthSynergy"] = 121,
            ["SpeedSynergy"] = 122,
            ["Explorer"] = 123,
            ["VesselTrail"] = 124,
            ["SlowResistance"] = 125,
            ["SlowImmunity"] = 126,
            ["TumbleBee"] = 127,
            ["BagOfSouls"] = 128,
            ["Acrobat"] = 129,
            ["PushVolumeImmunity"] = 130,
            ["WindResistance"] = 131,
            ["WindImmunity"] = 132,
            ["RollCharge"] = 133,
            ["MultiDodge"] = 134,
            ["EmeraldDivination"] = 135,
            ["DeathBarter"] = 136,
            ["ResurrectionSurge"] = 137,
            ["Huge"] = 138,
            ["ResurrectSurroundingMobs"] = 139,
            ["Invisible"] = 140,
            ["PoisonFocus"] = 141,
            ["FireFocus"] = 142,
            ["SoulFocus"] = 143,
            ["LightningFocus"] = 144,
            ["Flee"] = 145,
            ["BeastSurge"] = 146,
            ["BeastBurst"] = 147,
            ["BeastBoss"] = 148,
            ["Reckless"] = 149,
            ["CurrentImmunity"] = 150,
            ["CurrentResistance"] = 151,
            ["ThriveUnderPressure"] = 152,
            ["VoidBlast"] = 153,
            ["ShulkerSentry"] = 154,
            ["LuckOfTheSea"] = 155,
            ["UnderwaterImmunity"] = 156,
            ["PlayerIdle"] = 157,
            ["BardIdle"] = 158,
            ["BardUnique1Idle"] = 159,
            ["PassiveRegen"] = 160,
            ["VoidStrikeImmunity"] = 161,
        };

        /// <summary>Every skill a melee weapon in the game has built in: what a custom one can pick.</summary>
        public static readonly IReadOnlyList<string> SKILLS = new[]
        {
            "Backstabber",
            "BaneOfIllagers",
            "BusyBee",
            "Chains",
            "Committed",
            "CriticalHit",
            "DynamoMelee",
            "Echo",
            "EnigmaResonatorMelee",
            "Exploding",
            "FireAspect",
            "Freezing",
            "GravityMelee",
            "Heavyweight",
            "JunglePoisonMelee",
            "Leeching",
            "Looting",
            "PoisonedMelee",
            "Prospector",
            "RadianceMelee",
            "Rampaging",
            "Rushdown",
            "SharedPain",
            "Sharpness",
            "Shockwave",
            "Smiting",
            "SoulSiphon",
            "SpongeStrike",
            "Stunning",
            "Swirling",
            "Thundering",
            "VoidTouchedMelee",
            "Weakening",
        };

        /// <summary>Every property line a melee weapon in the game shows, by its ItemType key, with its English.</summary>
        public static readonly IReadOnlyDictionary<string, string> LINES = new Dictionary<string, string>
        {
            ["continuous_attacks"] = "Continuous attacks",
            ["dual_wield"] = "Dual Wield",
            ["fast_thrusts"] = "Fast Thrusts",
            ["great_pushback"] = "Great Pushback",
            ["great_splash"] = "Great Splash",
            ["long_continuous_attacks"] = "Long Continuous Attacks",
            ["long_melee_reach"] = "Long Melee Reach",
            ["longer_melee_reach"] = "Longer Melee Reach",
            ["powerful_pushback"] = "Powerful Pushback",
            ["rapid_slashes"] = "Rapid Slashes",
            ["relentless_combo"] = "Relentless Combo",
            ["reliable_combo"] = "Reliable Combo",
            ["slow_but_powerful"] = "Slow but Powerful",
            ["spin_attack"] = "Spin attack",
            ["spin_attack_move"] = "Spin attack move",
            ["stylish_combo"] = "Stylish Combo",
            ["thrust_attack"] = "Thrust attack",
            ["turbo_punches"] = "Turbo Punches",
            ["powerful_combo"] = "Very powerful combo",
        };

        /// <summary>Each game melee weapon's own built-in skills (name, level) and property lines (keys).</summary>
        public static readonly IReadOnlyDictionary<string, (IReadOnlyList<(string skill, int level)> skills, IReadOnlyList<string> lines)> WEAPONS =
            new Dictionary<string, (IReadOnlyList<(string, int)>, IReadOnlyList<string>)>(System.StringComparer.OrdinalIgnoreCase)
        {
            ["Anchor"] = (new (string, int)[] { ("Heavyweight", 1), ("GravityMelee", 1) }, new string[] { "slow_but_powerful" }),
            ["Anchor_Unique1"] = (new (string, int)[] { ("JunglePoisonMelee", 1), ("Heavyweight", 1), ("GravityMelee", 1) }, new string[] { "slow_but_powerful" }),
            ["Axe"] = (new (string, int)[] { }, new string[] { "spin_attack_move" }),
            ["Axe_Unique1"] = (new (string, int)[] { ("FireAspect", 1) }, new string[] { "spin_attack_move" }),
            ["Axe_Unique2"] = (new (string, int)[] { ("Stunning", 1) }, new string[] { "spin_attack_move" }),
            ["Backstabber"] = (new (string, int)[] { ("Backstabber", 1) }, new string[] { }),
            ["Backstabber_Unique1"] = (new (string, int)[] { ("Backstabber", 1), ("Echo", 1) }, new string[] { }),
            ["Battlestaff"] = (new (string, int)[] { }, new string[] { "stylish_combo" }),
            ["Battlestaff_Unique1"] = (new (string, int)[] { ("Committed", 1) }, new string[] { "stylish_combo" }),
            ["Battlestaff_Unique2"] = (new (string, int)[] { ("Exploding", 1) }, new string[] { "stylish_combo" }),
            ["Boneclub"] = (new (string, int)[] { }, new string[] { "great_pushback" }),
            ["Boneclub_Unique1"] = (new (string, int)[] { ("BaneOfIllagers", 1) }, new string[] { "great_pushback" }),
            ["Chainsword"] = (new (string, int)[] { }, new string[] { "continuous_attacks" }),
            ["Chainsword_Unique1"] = (new (string, int)[] { }, new string[] { "long_continuous_attacks" }),
            ["Claymore"] = (new (string, int)[] { }, new string[] { "powerful_pushback" }),
            ["Claymore_Unique1"] = (new (string, int)[] { ("Leeching", 1) }, new string[] { "powerful_pushback" }),
            ["Claymore_Unique2"] = (new (string, int)[] { ("Sharpness", 1) }, new string[] { "powerful_pushback" }),
            ["Claymore_Unique3"] = (new (string, int)[] { ("DynamoMelee", 1) }, new string[] { "powerful_pushback" }),
            ["Claymore_Winter1"] = (new (string, int)[] { ("Sharpness", 1) }, new string[] { "powerful_pushback" }),
            ["CoralBlade"] = (new (string, int)[] { }, new string[] { "rapid_slashes" }),
            ["CoralBlade_Unique1"] = (new (string, int)[] { ("SpongeStrike", 1) }, new string[] { "rapid_slashes" }),
            ["Cutlass"] = (new (string, int)[] { }, new string[] { "reliable_combo" }),
            ["Cutlass_Unique1"] = (new (string, int)[] { ("Weakening", 1) }, new string[] { "reliable_combo" }),
            ["Cutlass_Unique2"] = (new (string, int)[] { ("Rampaging", 1) }, new string[] { "reliable_combo" }),
            ["Cutlass_Year1"] = (new (string, int)[] { ("Rampaging", 1) }, new string[] { "reliable_combo" }),
            ["Daggers"] = (new (string, int)[] { }, new string[] { "dual_wield" }),
            ["Daggers_Unique1"] = (new (string, int)[] { ("Freezing", 1) }, new string[] { "dual_wield" }),
            ["Daggers_Unique2"] = (new (string, int)[] { ("EnigmaResonatorMelee", 1) }, new string[] { "dual_wield" }),
            ["Daggers_Unique3"] = (new (string, int)[] { ("Swirling", 1) }, new string[] { "dual_wield" }),
            ["DoubleAxe"] = (new (string, int)[] { }, new string[] { "spin_attack" }),
            ["DoubleAxe_Unique1"] = (new (string, int)[] { ("Shockwave", 1) }, new string[] { "spin_attack" }),
            ["DoubleAxe_Unique2"] = (new (string, int)[] { ("Exploding", 1) }, new string[] { "spin_attack" }),
            ["Gauntlets"] = (new (string, int)[] { }, new string[] { "relentless_combo" }),
            ["Gauntlets_Unique1"] = (new (string, int)[] { ("EnigmaResonatorMelee", 1) }, new string[] { "relentless_combo" }),
            ["Gauntlets_Unique2"] = (new (string, int)[] { ("Rampaging", 1) }, new string[] { "relentless_combo" }),
            ["Gauntlets_Unique3"] = (new (string, int)[] { }, new string[] { "turbo_punches" }),
            ["Glaive"] = (new (string, int)[] { }, new string[] { "longer_melee_reach" }),
            ["Glaive_Spooky2"] = (new (string, int)[] { ("Smiting", 1) }, new string[] { "longer_melee_reach" }),
            ["Glaive_Unique1"] = (new (string, int)[] { ("Smiting", 1) }, new string[] { "longer_melee_reach" }),
            ["Glaive_Unique2"] = (new (string, int)[] { ("PoisonedMelee", 1) }, new string[] { "longer_melee_reach" }),
            ["Hammer"] = (new (string, int)[] { }, new string[] { "great_splash" }),
            ["Hammer_Unique1"] = (new (string, int)[] { ("Thundering", 1) }, new string[] { "great_splash" }),
            ["Hammer_Unique2"] = (new (string, int)[] { ("GravityMelee", 1) }, new string[] { "great_splash" }),
            ["Katana"] = (new (string, int)[] { }, new string[] { }),
            ["Katana_Unique1"] = (new (string, int)[] { ("CriticalHit", 1) }, new string[] { }),
            ["Katana_Unique2"] = (new (string, int)[] { ("Smiting", 1) }, new string[] { }),
            ["Mace"] = (new (string, int)[] { }, new string[] { }),
            ["Mace_Unique1"] = (new (string, int)[] { ("RadianceMelee", 1) }, new string[] { }),
            ["Mace_Unique2"] = (new (string, int)[] { ("Chains", 1) }, new string[] { }),
            ["ObsidianClaymore"] = (new (string, int)[] { }, new string[] { "powerful_combo" }),
            ["ObsidianClaymore_Unique1"] = (new (string, int)[] { ("SharedPain", 1) }, new string[] { "powerful_combo" }),
            ["Pickaxe"] = (new (string, int)[] { }, new string[] { }),
            ["Pickaxe_Unique1"] = (new (string, int)[] { ("Prospector", 1) }, new string[] { }),
            ["Rapier"] = (new (string, int)[] { }, new string[] { "fast_thrusts" }),
            ["Rapier_Unique1"] = (new (string, int)[] { ("BusyBee", 1) }, new string[] { "fast_thrusts" }),
            ["Rapier_Unique2"] = (new (string, int)[] { ("Freezing", 1) }, new string[] { "fast_thrusts" }),
            ["Sickles"] = (new (string, int)[] { }, new string[] { "dual_wield" }),
            ["Sickles_Unique1"] = (new (string, int)[] { ("PoisonedMelee", 1) }, new string[] { "dual_wield" }),
            ["Sickles_Unique2"] = (new (string, int)[] { ("Prospector", 1) }, new string[] { "dual_wield" }),
            ["SkeletonHammer"] = (new (string, int)[] { ("GravityMelee", 1) }, new string[] { "great_splash" }),
            ["SoulKnife"] = (new (string, int)[] { }, new string[] { "thrust_attack" }),
            ["SoulKnife_Unique1"] = (new (string, int)[] { ("Committed", 1) }, new string[] { "thrust_attack" }),
            ["SoulKnife_Unique2"] = (new (string, int)[] { ("SoulSiphon", 1) }, new string[] { "thrust_attack" }),
            ["SoulScythe"] = (new (string, int)[] { }, new string[] { }),
            ["SoulScythe_Spooky2"] = (new (string, int)[] { ("Freezing", 1) }, new string[] { }),
            ["SoulScythe_Unique1"] = (new (string, int)[] { ("Chains", 1) }, new string[] { }),
            ["SoulScythe_Unique2"] = (new (string, int)[] { ("Freezing", 1) }, new string[] { }),
            ["Spear"] = (new (string, int)[] { }, new string[] { "long_melee_reach" }),
            ["Spear_spooky2"] = (new (string, int)[] { ("Echo", 1) }, new string[] { "long_melee_reach" }),
            ["Spear_Unique1"] = (new (string, int)[] { ("Echo", 1) }, new string[] { "long_melee_reach" }),
            ["Spear_Unique2"] = (new (string, int)[] { ("Looting", 1) }, new string[] { "long_melee_reach" }),
            ["Sword"] = (new (string, int)[] { }, new string[] { }),
            ["Sword_Spooky1"] = (new (string, int)[] { ("CriticalHit", 1) }, new string[] { }),
            ["Sword_Unique1"] = (new (string, int)[] { ("Sharpness", 1) }, new string[] { }),
            ["Sword_Unique2"] = (new (string, int)[] { ("CriticalHit", 1) }, new string[] { }),
            ["TempestKnife"] = (new (string, int)[] { ("Rushdown", 1) }, new string[] { }),
            ["TempestKnife_Unique1"] = (new (string, int)[] { ("Rushdown", 1), ("Committed", 1) }, new string[] { }),
            ["TempestKnife_Unique2"] = (new (string, int)[] { ("Rushdown", 1), ("Freezing", 1) }, new string[] { }),
            ["VoidTouchedBlades"] = (new (string, int)[] { ("VoidTouchedMelee", 1) }, new string[] { }),
            ["VoidTouchedBlades_Unique1"] = (new (string, int)[] { ("Leeching", 1), ("VoidTouchedMelee", 1) }, new string[] { }),
            ["Whip"] = (new (string, int)[] { }, new string[] { "longer_melee_reach" }),
            ["Whip_Unique1"] = (new (string, int)[] { ("JunglePoisonMelee", 1) }, new string[] { "longer_melee_reach" }),
        };
    }
}
