//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCDSaveEdit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCDSaveEdit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About MCD Reborn.
        /// </summary>
        public static string ABOUT_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("ABOUT_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string ALL_FILES {
            get {
                return ResourceManager.GetString("ALL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recolor Gear.
        /// </summary>
        public static string CUSTOM_SKINS_TAB {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear.
        /// </summary>
        public static string CUSTOM_SKINS_GEAR {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_GEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string CUSTOM_SKINS_INSTALLED {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export PNG….
        /// </summary>
        public static string CUSTOM_SKINS_EXPORT {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Open in Designer.
        /// </summary>
        public static string CUSTOM_SKINS_DESIGNER {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_DESIGNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply PNG….
        /// </summary>
        public static string CUSTOM_SKINS_APPLY {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string CUSTOM_SKINS_REMOVE {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export a texture, recolour it at mcddesigner.vercel.app, then apply the PNG. Applying writes a mod pak beside the game's own; the originals are never modified, and Remove undoes it completely..
        /// </summary>
        public static string CUSTOM_SKINS_HINT {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the game content to use custom skins..
        /// </summary>
        public static string CUSTOM_SKINS_NO_CONTENT {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_NO_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a piece of gear on the left..
        /// </summary>
        public static string CUSTOM_SKINS_PICK_ONE {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_PICK_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No colour texture found for this one..
        /// </summary>
        public static string CUSTOM_SKINS_NO_TEXTURE {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_NO_TEXTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Apply from Designer.
        /// </summary>
        public static string CUSTOM_SKINS_PASTE {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or use files:.
        /// </summary>
        public static string CUSTOM_SKINS_FILES {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clipboard does not hold a texture from the Designer..
        /// </summary>
        public static string CUSTOM_SKINS_NOTHING_COPIED {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_NOTHING_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Designer could not be opened, so the link was copied to the clipboard instead..
        /// </summary>
        public static string CUSTOM_SKINS_LINK_COPIED {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_LINK_COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a mod pak….
        /// </summary>
        public static string CUSTOM_SKINS_ADD_PAK {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_ADD_PAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the mods folder.
        /// </summary>
        public static string CUSTOM_SKINS_OPEN_MODS {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_OPEN_MODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added “{0}” to mods. Close and reopen the game to see it..
        /// </summary>
        public static string CUSTOM_SKINS_PAK_ADDED {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_PAK_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “{0}” is already in mods. Replace it?.
        /// </summary>
        public static string CUSTOM_SKINS_PAK_REPLACE {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_PAK_REPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added by you.
        /// </summary>
        public static string CUSTOM_SKINS_MANUAL_TAG {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_MANUAL_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods load from the mods folder beside the game's own paks. Close the game before adding one, and on the Minecraft Launcher start Dungeons.exe directly – launching through the launcher removes mods..
        /// </summary>
        public static string CUSTOM_SKINS_MODS_NOTE {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_MODS_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search….
        /// </summary>
        public static string SEARCH_HINT {
            get {
                return ResourceManager.GetString("SEARCH_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        public static string ARMOR_DEFAULTS {
            get {
                return ResourceManager.GetString("ARMOR_DEFAULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace this armor's properties with the ones it drops with in game.
        /// </summary>
        public static string ARMOR_DEFAULTS_TOOLTIP {
            get {
                return ResourceManager.GetString("ARMOR_DEFAULTS_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Skins.
        /// </summary>
        public static string HERO_TAB {
            get {
                return ResourceManager.GetString("HERO_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroes.
        /// </summary>
        public static string HERO_HEROES {
            get {
                return ResourceManager.GetString("HERO_HEROES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a hero on the left..
        /// </summary>
        public static string HERO_PICK_ONE {
            get {
                return ResourceManager.GetString("HERO_PICK_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play as this hero.
        /// </summary>
        public static string HERO_PLAY_AS {
            get {
                return ResourceManager.GetString("HERO_PLAY_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently: {0}.
        /// </summary>
        public static string HERO_CURRENT {
            get {
                return ResourceManager.GetString("HERO_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now playing as “{0}”. Save the file to keep it..
        /// </summary>
        public static string HERO_NOW_PLAYING {
            get {
                return ResourceManager.GetString("HERO_NOW_PLAYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wear your own skin.
        /// </summary>
        public static string HERO_OWN_SKIN {
            get {
                return ResourceManager.GetString("HERO_OWN_SKIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide the armour I have equipped, so the skin shows.
        /// </summary>
        public static string HERO_HIDE_ARMOUR {
            get {
                return ResourceManager.GetString("HERO_HIDE_ARMOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide equipped armour (nothing equipped).
        /// </summary>
        public static string HERO_NO_ARMOUR_EQUIPPED {
            get {
                return ResourceManager.GetString("HERO_NO_ARMOUR_EQUIPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed as “{0}”, with {1} armour texture(s) hidden. Close and re....
        /// </summary>
        public static string HERO_APPLIED_HIDDEN {
            get {
                return ResourceManager.GetString("HERO_APPLIED_HIDDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The save records which hero you play as; changing it here needs no ....
        /// </summary>
        public static string HERO_HINT {
            get {
                return ResourceManager.GetString("HERO_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any 64×64 Minecraft skin works. This writes a mod pak beside the ga....
        /// </summary>
        public static string HERO_OWN_SKIN_HINT {
            get {
                return ResourceManager.GetString("HERO_OWN_SKIN_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armour:.
        /// </summary>
        public static string HERO_ARMOUR {
            get {
                return ResourceManager.GetString("HERO_ARMOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave armour as it is.
        /// </summary>
        public static string HERO_ARMOUR_KEEP {
            get {
                return ResourceManager.GetString("HERO_ARMOUR_KEEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide the armour I have equipped.
        /// </summary>
        public static string HERO_ARMOUR_EQUIPPED {
            get {
                return ResourceManager.GetString("HERO_ARMOUR_EQUIPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide all armour, whatever I wear.
        /// </summary>
        public static string HERO_ARMOUR_ALL {
            get {
                return ResourceManager.GetString("HERO_ARMOUR_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides {0} armour textures in one pak, so the skin shows whatever yo....
        /// </summary>
        public static string HERO_ARMOUR_ALL_NOTE {
            get {
                return ResourceManager.GetString("HERO_ARMOUR_ALL_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a character save first.
        /// </summary>
        public static string HERO_NO_SAVE {
            get {
                return ResourceManager.GetString("HERO_NO_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string HERO_RESET {
            get {
                return ResourceManager.GetString("HERO_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A skin of your own is installed.
        /// </summary>
        public static string HERO_CUSTOM_INSTALLED {
            get {
                return ResourceManager.GetString("HERO_CUSTOM_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed the installed skin and brought the armour back..
        /// </summary>
        public static string HERO_RESET_SKIN {
            get {
                return ResourceManager.GetString("HERO_RESET_SKIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put the hero back to how the save had it..
        /// </summary>
        public static string HERO_RESET_HERO {
            get {
                return ResourceManager.GetString("HERO_RESET_HERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to put back..
        /// </summary>
        public static string HERO_RESET_NOTHING {
            get {
                return ResourceManager.GetString("HERO_RESET_NOTHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying a skin makes every armour invisible.
        /// </summary>
        public static string HERO_ARMOUR_WARNING {
            get {
                return ResourceManager.GetString("HERO_ARMOUR_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show armours.
        /// </summary>
        public static string ARMOUR_SHOW {
            get {
                return ResourceManager.GetString("ARMOUR_SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armour is drawn normally..
        /// </summary>
        public static string ARMOUR_SHOWN_HINT {
            get {
                return ResourceManager.GetString("ARMOUR_SHOWN_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every armour is invisible, so a hero skin can be seen. Your gear is....
        /// </summary>
        public static string ARMOUR_HIDDEN_HINT {
            get {
                return ResourceManager.GetString("ARMOUR_HIDDEN_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armours are visible again..
        /// </summary>
        public static string HERO_RESET_ARMOUR {
            get {
                return ResourceManager.GetString("HERO_RESET_ARMOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed as “{0}”. Armour is still drawn over it - untick Show arm....
        /// </summary>
        public static string HERO_APPLIED_ARMOUR_SHOWN {
            get {
                return ResourceManager.GetString("HERO_APPLIED_ARMOUR_SHOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture.
        /// </summary>
        public static string HERO_VIEW_TEXTURE {
            get {
                return ResourceManager.GetString("HERO_VIEW_TEXTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string HERO_VIEW_MODEL {
            get {
                return ResourceManager.GetString("HERO_VIEW_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recentre.
        /// </summary>
        public static string HERO_RECENTRE {
            get {
                return ResourceManager.GetString("HERO_RECENTRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to turn.
        /// </summary>
        public static string HERO_DRAG_HINT {
            get {
                return ResourceManager.GetString("HERO_DRAG_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import skin PNG….
        /// </summary>
        public static string HERO_IMPORT_SKIN {
            get {
                return ResourceManager.GetString("HERO_IMPORT_SKIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Designer.
        /// </summary>
        public static string HERO_OPEN_DESIGNER {
            get {
                return ResourceManager.GetString("HERO_OPEN_DESIGNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply from Designer.
        /// </summary>
        public static string HERO_APPLY_DESIGNER {
            get {
                return ResourceManager.GetString("HERO_APPLY_DESIGNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or edit first:.
        /// </summary>
        public static string HERO_OR_EDIT {
            get {
                return ResourceManager.GetString("HERO_OR_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wear this skin.
        /// </summary>
        public static string HERO_WEAR_THIS {
            get {
                return ResourceManager.GetString("HERO_WEAR_THIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A skin you imported.
        /// </summary>
        public static string HERO_YOUR_SKIN {
            get {
                return ResourceManager.GetString("HERO_YOUR_SKIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget.
        /// </summary>
        public static string HERO_FORGET {
            get {
                return ResourceManager.GetString("HERO_FORGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget “{0}”? The file is removed from your skins; anything already....
        /// </summary>
        public static string HERO_FORGET_SKIN {
            get {
                return ResourceManager.GetString("HERO_FORGET_SKIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported {0}. Pick it on the left to wear it..
        /// </summary>
        public static string HERO_IMPORTED {
            get {
                return ResourceManager.GetString("HERO_IMPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now wearing “{0}”. Restart the game to see it..
        /// </summary>
        public static string HERO_NOW_WEARING {
            get {
                return ResourceManager.GetString("HERO_NOW_WEARING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now wearing “{0}”, but armour is still drawn over it - untick Show ....
        /// </summary>
        public static string HERO_NOW_WEARING_COVERED {
            get {
                return ResourceManager.GetString("HERO_NOW_WEARING_COVERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your skin, on {0}.
        /// </summary>
        public static string HERO_WORN_ON {
            get {
                return ResourceManager.GetString("HERO_WORN_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing installed yet..
        /// </summary>
        public static string CUSTOM_SKINS_NONE_INSTALLED {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_NONE_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved to {0}.
        /// </summary>
        public static string CUSTOM_SKINS_EXPORTED {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_EXPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed as “{0}”. Restart the game to see it..
        /// </summary>
        public static string CUSTOM_SKINS_APPLIED {
            get {
                return ResourceManager.GetString("CUSTOM_SKINS_APPLIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ALL_ITEMS_FILTER {
            get {
                return ResourceManager.GetString("ALL_ITEMS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip.
        /// </summary>
        public static string EQUIP {
            get {
                return ResourceManager.GetString("EQUIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip in Slot {0}.
        /// </summary>
        public static string EQUIP_IN_SLOT {
            get {
                return ResourceManager.GetString("EQUIP_IN_SLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OTHER_ENCHANTMENTS_FILTER {
            get {
                return ResourceManager.GetString("OTHER_ENCHANTMENTS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip over.
        /// </summary>
        public static string EQUIP_OVER {
            get {
                return ResourceManager.GetString("EQUIP_OVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip over Slot {0}.
        /// </summary>
        public static string EQUIP_OVER_IN_SLOT {
            get {
                return ResourceManager.GetString("EQUIP_OVER_IN_SLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unequip.
        /// </summary>
        public static string UNEQUIP {
            get {
                return ResourceManager.GetString("UNEQUIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no room in the inventory to unequip this: it already holds the maximum of {0} items.
        /// </summary>
        public static string INVENTORY_FULL_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("INVENTORY_FULL_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCD Reborn.
        /// </summary>
        public static string APPLICATION_TITLE {
            get {
                return ResourceManager.GetString("APPLICATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        public static string ARMOR_ITEMS_FILTER {
            get {
                return ResourceManager.GetString("ARMOR_ITEMS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrows.
        /// </summary>
        public static string ARROWS {
            get {
                return ResourceManager.GetString("ARROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact.
        /// </summary>
        public static string ARTIFACT_ITEMS_FILTER {
            get {
                return ResourceManager.GetString("ARTIFACT_ITEMS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempts Left.
        /// </summary>
        public static string ATTEMPTS_LEFT {
            get {
                return ResourceManager.GetString("ATTEMPTS_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta _Update.
        /// </summary>
        public static string BETA_UPDATE_MENU_ITEM_HEADER {
            get {
                return ResourceManager.GetString("BETA_UPDATE_MENU_ITEM_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        public static string BETA_VERSION_LABEL {
            get {
                return ResourceManager.GetString("BETA_VERSION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosses Defeated.
        /// </summary>
        public static string BOSSES_DEFEATED {
            get {
                return ResourceManager.GetString("BOSSES_DEFEATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character File format not recognized. Please select a valid Character File..
        /// </summary>
        public static string CHARACTER_FILE_FORMAT_NOT_RECOGNIZED_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("CHARACTER_FILE_FORMAT_NOT_RECOGNIZED_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest.
        /// </summary>
        public static string CHEST {
            get {
                return ResourceManager.GetString("CHEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string COMMON {
            get {
                return ResourceManager.GetString("COMMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Apocalypse Plus:.
        /// </summary>
        public static string COMPLETED_APOCALYPSE_PLUS {
            get {
                return ResourceManager.GetString("COMPLETED_APOCALYPSE_PLUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Difficulty:.
        /// </summary>
        public static string COMPLETED_DIFFICULTY {
            get {
                return ResourceManager.GetString("COMPLETED_DIFFICULTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Threat Level:.
        /// </summary>
        public static string COMPLETED_THREAT_LEVEL {
            get {
                return ResourceManager.GetString("COMPLETED_THREAT_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creeping Winter.
        /// </summary>
        public static string CREEPING_WINTER {
            get {
                return ResourceManager.GetString("CREEPING_WINTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Floor.
        /// </summary>
        public static string CURRENT_FLOOR {
            get {
                return ResourceManager.GetString("CURRENT_FLOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypted Character Save files.
        /// </summary>
        public static string DECRYPTED_CHARACTER_SAVE_FILES {
            get {
                return ResourceManager.GetString("DECRYPTED_CHARACTER_SAVE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure.
        /// </summary>
        public static string DIFFICULTY_ADVENTURE {
            get {
                return ResourceManager.GetString("DIFFICULTY_ADVENTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apocalypse.
        /// </summary>
        public static string DIFFICULTY_APOCALYPSE {
            get {
                return ResourceManager.GetString("DIFFICULTY_APOCALYPSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DIFFICULTY_DEFAULT {
            get {
                return ResourceManager.GetString("DIFFICULTY_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string DUPLICATE {
            get {
                return ResourceManager.GetString("DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emeralds.
        /// </summary>
        public static string EMERALDS {
            get {
                return ResourceManager.GetString("EMERALDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enchanted.
        /// </summary>
        public static string ENCHANTED_ITEMS_FILTER {
            get {
                return ResourceManager.GetString("ENCHANTED_ITEMS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted Character Save files.
        /// </summary>
        public static string ENCRYPTED_CHARACTER_SAVE_FILES {
            get {
                return ResourceManager.GetString("ENCRYPTED_CHARACTER_SAVE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to encrypt the json data..
        /// </summary>
        public static string FAILED_TO_ENCRYPT_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("FAILED_TO_ENCRYPT_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load game content..
        /// </summary>
        public static string FAILED_TO_LOAD_GAME_CONTENT_ERROR_TITLE {
            get {
                return ResourceManager.GetString("FAILED_TO_LOAD_GAME_CONTENT_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was not in an expected format..
        /// </summary>
        public static string FAILED_TO_PARSE_FILE_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("FAILED_TO_PARSE_FILE_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content of file \&quot;{0}\&quot; could not be converted to a supported format..
        /// </summary>
        public static string FILE_DECRYPT_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("FILE_DECRYPT_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File doesn&apos;t exist..
        /// </summary>
        public static string FILE_DOESNT_EXIST_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("FILE_DOESNT_EXIST_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a file..
        /// </summary>
        public static string FILE_DROP_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("FILE_DROP_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file \&quot;{0}\&quot; was in an unexpected format..
        /// </summary>
        public static string FILE_IN_UNEXPECTED_FORMAT_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("FILE_IN_UNEXPECTED_FORMAT_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Floor.
        /// </summary>
        public static string FINAL_FLOOR {
            get {
                return ResourceManager.GetString("FINAL_FLOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenges.
        /// </summary>
        public static string FLOOR_CHALLENGES {
            get {
                return ResourceManager.GetString("FLOOR_CHALLENGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewards.
        /// </summary>
        public static string FLOOR_REWARDS {
            get {
                return ResourceManager.GetString("FLOOR_REWARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile.
        /// </summary>
        public static string FLOOR_TILE {
            get {
                return ResourceManager.GetString("FLOOR_TILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string FLOOR_TYPE {
            get {
                return ResourceManager.GetString("FLOOR_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Files.
        /// </summary>
        public static string GAME_FILES_WINDOW_GROUPBOX_HEADER {
            get {
                return ResourceManager.GetString("GAME_FILES_WINDOW_GROUPBOX_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find game content files in the default install location. Please provide the path to the game files or launch with no game content and limited features..
        /// </summary>
        public static string GAME_FILES_WINDOW_MESSAGE {
            get {
                return ResourceManager.GetString("GAME_FILES_WINDOW_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No game content.
        /// </summary>
        public static string GAME_FILES_WINDOW_NO_CONTENT_BUTTON {
            get {
                return ResourceManager.GetString("GAME_FILES_WINDOW_NO_CONTENT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string GAME_FILES_WINDOW_TEXTBOX_LABEL {
            get {
                return ResourceManager.GetString("GAME_FILES_WINDOW_TEXTBOX_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch using game content.
        /// </summary>
        public static string GAME_FILES_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("GAME_FILES_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gifted.
        /// </summary>
        public static string GIFTED {
            get {
                return ResourceManager.GetString("GIFTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gilded.
        /// </summary>
        public static string GILDED {
            get {
                return ResourceManager.GetString("GILDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give up Tower Run.
        /// </summary>
        public static string GIVE_UP_TOWER_RUN {
            get {
                return ResourceManager.GetString("GIVE_UP_TOWER_RUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Howling Peaks.
        /// </summary>
        public static string HOWLING_PEAKS {
            get {
                return ResourceManager.GetString("HOWLING_PEAKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string INVENTORY {
            get {
                return ResourceManager.GetString("INVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Island Realms.
        /// </summary>
        public static string ISLAND_REALMS {
            get {
                return ResourceManager.GetString("ISLAND_REALMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item was deleted..
        /// </summary>
        public static string ITEM_WAS_DELETED_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("ITEM_WAS_DELETED_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items: {0}/{1} Max.
        /// </summary>
        public static string ITEMS_COUNT_LABEL {
            get {
                return ResourceManager.GetString("ITEMS_COUNT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jungle Awakens.
        /// </summary>
        public static string JUNGLE_AWAKENS {
            get {
                return ResourceManager.GetString("JUNGLE_AWAKENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch with no game content and limited features?.
        /// </summary>
        public static string LAUNCH_WITH_LIMITED_FEATURES_QUESTION {
            get {
                return ResourceManager.GetString("LAUNCH_WITH_LIMITED_FEATURES_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string LEVEL {
            get {
                return ResourceManager.GetString("LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mainland.
        /// </summary>
        public static string MAINLAND {
            get {
                return ResourceManager.GetString("MAINLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCD {0}.
        /// </summary>
        public static string MCD_VERSION_FORMAT {
            get {
                return ResourceManager.GetString("MCD_VERSION_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        public static string MELEE_ITEMS_FILTER {
            get {
                return ResourceManager.GetString("MELEE_ITEMS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MENU_ITEM_ABOUT {
            get {
                return ResourceManager.GetString("MENU_ITEM_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MENU_ITEM_FILE {
            get {
                return ResourceManager.GetString("MENU_ITEM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get New Version.
        /// </summary>
        public static string MENU_ITEM_GET_NEW_VERSION {
            get {
                return ResourceManager.GetString("MENU_ITEM_GET_NEW_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missions.
        /// </summary>
        public static string MISSIONS {
            get {
                return ResourceManager.GetString("MISSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mob Kills.
        /// </summary>
        public static string MOB_KILLS {
            get {
                return ResourceManager.GetString("MOB_KILLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Inventory.
        /// </summary>
        public static string MOVE_TO_INVENTORY {
            get {
                return ResourceManager.GetString("MOVE_TO_INVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Storage.
        /// </summary>
        public static string MOVE_TO_STORAGE {
            get {
                return ResourceManager.GetString("MOVE_TO_STORAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Floor {0} / {1} : {2}.
        /// </summary>
        public static string NEXT_LEVEL_LABEL {
            get {
                return ResourceManager.GetString("NEXT_LEVEL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find game content files at the given path..
        /// </summary>
        public static string NO_GAME_FILES_FOUND_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("NO_GAME_FILES_FOUND_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown game version.
        /// </summary>
        public static string NO_GAME_VERSION_DETECTED {
            get {
                return ResourceManager.GetString("NO_GAME_VERSION_DETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Completed.
        /// </summary>
        public static string NOT_COMPLETED {
            get {
                return ResourceManager.GetString("NOT_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old.
        /// </summary>
        public static string OLD_VERSION_LABEL {
            get {
                return ResourceManager.GetString("OLD_VERSION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure you have the latest version..
        /// </summary>
        public static string PLEASE_HAVE_LATEST_VERSION {
            get {
                return ResourceManager.GetString("PLEASE_HAVE_LATEST_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string POWER {
            get {
                return ResourceManager.GetString("POWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerful.
        /// </summary>
        public static string POWERFUL {
            get {
                return ResourceManager.GetString("POWERFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Stat Counters.
        /// </summary>
        public static string PROGRESS_STAT_COUNTERS {
            get {
                return ResourceManager.GetString("PROGRESS_STAT_COUNTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        public static string RANGED_ITEMS_FILTER {
            get {
                return ResourceManager.GetString("RANGED_ITEMS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        public static string RARE {
            get {
                return ResourceManager.GetString("RARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed.
        /// </summary>
        public static string SEED {
            get {
                return ResourceManager.GetString("SEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Armor.
        /// </summary>
        public static string SELECT_ARMOR {
            get {
                return ResourceManager.GetString("SELECT_ARMOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Armor Property.
        /// </summary>
        public static string SELECT_ARMOR_PROPERTY {
            get {
                return ResourceManager.GetString("SELECT_ARMOR_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Artifact.
        /// </summary>
        public static string SELECT_ARTIFACT {
            get {
                return ResourceManager.GetString("SELECT_ARTIFACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Enchantment.
        /// </summary>
        public static string SELECT_ENCHANTMENT {
            get {
                return ResourceManager.GetString("SELECT_ENCHANTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Item.
        /// </summary>
        public static string SELECT_ITEM {
            get {
                return ResourceManager.GetString("SELECT_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Melee Weapon.
        /// </summary>
        public static string SELECT_MELEE_WEAPON {
            get {
                return ResourceManager.GetString("SELECT_MELEE_WEAPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Ranged Weapon.
        /// </summary>
        public static string SELECT_RANGED_WEAPON {
            get {
                return ResourceManager.GetString("SELECT_RANGED_WEAPON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Update.
        /// </summary>
        public static string STABLE_UPDATE_MENU_ITEM_HEADER {
            get {
                return ResourceManager.GetString("STABLE_UPDATE_MENU_ITEM_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stable.
        /// </summary>
        public static string STABLE_VERSION_LABEL {
            get {
                return ResourceManager.GetString("STABLE_VERSION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Tower Run.
        /// </summary>
        public static string START_TOWER_RUN {
            get {
                return ResourceManager.GetString("START_TOWER_RUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats/Counters.
        /// </summary>
        public static string STATS_COUNTERS {
            get {
                return ResourceManager.GetString("STATS_COUNTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tower.
        /// </summary>
        public static string THE_TOWER {
            get {
                return ResourceManager.GetString("THE_TOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier.
        /// </summary>
        public static string TIER {
            get {
                return ResourceManager.GetString("TIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique.
        /// </summary>
        public static string UNIQUE {
            get {
                return ResourceManager.GetString("UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreleased.
        /// </summary>
        public static string UNRELEASED_VERSION_LABEL {
            get {
                return ResourceManager.GetString("UNRELEASED_VERSION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgraded.
        /// </summary>
        public static string UPGRADED {
            get {
                return ResourceManager.GetString("UPGRADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0} {1}.
        /// </summary>
        public static string VERSION_FORMAT {
            get {
                return ResourceManager.GetString("VERSION_FORMAT", resourceCulture);
            }
        }
    }
}
